// SPDX-License-Identifier: GPL-2.0 
/*-----------------------------------------------------------------------------
* C Header bank BASE definitions
*------------------------------------------------------------------------------
*/
#define CHAN_PROC_CFG_BASE_ADDR 0x0 /* 0 */
#define CHAN_PROC_FRAM_BASE_ADDR 0x2000 /* 8192 */
#define CHAN_PROC_SETUP_BASE_ADDR 0x4000 /* 16384 */
#define CHAN_PROC_SEQUENCE_TABLE_BASE_ADDR 0x6000 /* 24576 */

/*-----------------------------------------------------------------------------
* C Header bank register definitions for bank chan_proc_cfg 
* with prefix cfg_ @ address 0x0
*------------------------------------------------------------------------------
*/
/* Type = roInt  */
#define CFG_MAJOR_REVISION_ADDR 0x0 /* 0 */
#define CFG_MAJOR_REVISION_MASK 0xff000000 /* 4278190080 */
#define CFG_MAJOR_REVISION_OFFSET 0x18 /* 24 */
#define CFG_MAJOR_REVISION_WIDTH 0x8 /* 8 */
#define CFG_MAJOR_REVISION_DEFAULT 0x1 /* 1 */

/* Type = roInt  */
#define CFG_MINOR_REVISION_ADDR 0x0 /* 0 */
#define CFG_MINOR_REVISION_MASK 0xff0000 /* 16711680 */
#define CFG_MINOR_REVISION_OFFSET 0x10 /* 16 */
#define CFG_MINOR_REVISION_WIDTH 0x8 /* 8 */
#define CFG_MINOR_REVISION_DEFAULT 0x0 /* 0 */

/* Type = roInt  */
#define CFG_VERSION_REVISION_ADDR 0x0 /* 0 */
#define CFG_VERSION_REVISION_MASK 0xff00 /* 65280 */
#define CFG_VERSION_REVISION_OFFSET 0x8 /* 8 */
#define CFG_VERSION_REVISION_WIDTH 0x8 /* 8 */
#define CFG_VERSION_REVISION_DEFAULT 0x0 /* 0 */

/* Type = roDate  */
#define CFG_INTERNAL_REVISION_ADDR 0x4 /* 4 */
#define CFG_INTERNAL_REVISION_MASK 0xffffffff /* 4294967295 */
#define CFG_INTERNAL_REVISION_OFFSET 0x0 /* 0 */
#define CFG_INTERNAL_REVISION_WIDTH 0x20 /* 32 */
#define CFG_INTERNAL_REVISION_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define CFG_MAX_NUM_CC_ADDR 0x8 /* 8 */
#define CFG_MAX_NUM_CC_MASK 0xf /* 15 */
#define CFG_MAX_NUM_CC_OFFSET 0x0 /* 0 */
#define CFG_MAX_NUM_CC_WIDTH 0x4 /* 4 */
#define CFG_MAX_NUM_CC_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define CFG_MAX_NUM_ANTENNA_ADDR 0x8 /* 8 */
#define CFG_MAX_NUM_ANTENNA_MASK 0xf00 /* 3840 */
#define CFG_MAX_NUM_ANTENNA_OFFSET 0x8 /* 8 */
#define CFG_MAX_NUM_ANTENNA_WIDTH 0x4 /* 4 */
#define CFG_MAX_NUM_ANTENNA_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define CFG_MAX_ANTENNA_INTERLEAVE_ADDR 0x8 /* 8 */
#define CFG_MAX_ANTENNA_INTERLEAVE_MASK 0x70000 /* 458752 */
#define CFG_MAX_ANTENNA_INTERLEAVE_OFFSET 0x10 /* 16 */
#define CFG_MAX_ANTENNA_INTERLEAVE_WIDTH 0x3 /* 3 */
#define CFG_MAX_ANTENNA_INTERLEAVE_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CFG_MASTER_INT_ENABLE_ADDR 0x10 /* 16 */
#define CFG_MASTER_INT_ENABLE_MASK 0x1 /* 1 */
#define CFG_MASTER_INT_ENABLE_OFFSET 0x0 /* 0 */
#define CFG_MASTER_INT_ENABLE_WIDTH 0x1 /* 1 */
#define CFG_MASTER_INT_ENABLE_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CFG_DL_CC_UPDATE_TRIGGERED_EN_ADDR 0x14 /* 20 */
#define CFG_DL_CC_UPDATE_TRIGGERED_EN_MASK 0x1 /* 1 */
#define CFG_DL_CC_UPDATE_TRIGGERED_EN_OFFSET 0x0 /* 0 */
#define CFG_DL_CC_UPDATE_TRIGGERED_EN_WIDTH 0x1 /* 1 */
#define CFG_DL_CC_UPDATE_TRIGGERED_EN_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CFG_DL_SEQUENCE_ERROR_EN_ADDR 0x14 /* 20 */
#define CFG_DL_SEQUENCE_ERROR_EN_MASK 0x2 /* 2 */
#define CFG_DL_SEQUENCE_ERROR_EN_OFFSET 0x1 /* 1 */
#define CFG_DL_SEQUENCE_ERROR_EN_WIDTH 0x1 /* 1 */
#define CFG_DL_SEQUENCE_ERROR_EN_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CFG_DL_SEQUENCE_TABLE_ERROR_EN_ADDR 0x14 /* 20 */
#define CFG_DL_SEQUENCE_TABLE_ERROR_EN_MASK 0x4 /* 4 */
#define CFG_DL_SEQUENCE_TABLE_ERROR_EN_OFFSET 0x2 /* 2 */
#define CFG_DL_SEQUENCE_TABLE_ERROR_EN_WIDTH 0x1 /* 1 */
#define CFG_DL_SEQUENCE_TABLE_ERROR_EN_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CFG_UL_CC_UPDATE_TRIGGERED_EN_ADDR 0x14 /* 20 */
#define CFG_UL_CC_UPDATE_TRIGGERED_EN_MASK 0x100 /* 256 */
#define CFG_UL_CC_UPDATE_TRIGGERED_EN_OFFSET 0x8 /* 8 */
#define CFG_UL_CC_UPDATE_TRIGGERED_EN_WIDTH 0x1 /* 1 */
#define CFG_UL_CC_UPDATE_TRIGGERED_EN_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CFG_UL_SEQUENCE_ERROR_EN_ADDR 0x14 /* 20 */
#define CFG_UL_SEQUENCE_ERROR_EN_MASK 0x200 /* 512 */
#define CFG_UL_SEQUENCE_ERROR_EN_OFFSET 0x9 /* 9 */
#define CFG_UL_SEQUENCE_ERROR_EN_WIDTH 0x1 /* 1 */
#define CFG_UL_SEQUENCE_ERROR_EN_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CFG_UL_SEQUENCE_TABLE_ERROR_EN_ADDR 0x14 /* 20 */
#define CFG_UL_SEQUENCE_TABLE_ERROR_EN_MASK 0x400 /* 1024 */
#define CFG_UL_SEQUENCE_TABLE_ERROR_EN_OFFSET 0xa /* 10 */
#define CFG_UL_SEQUENCE_TABLE_ERROR_EN_WIDTH 0x1 /* 1 */
#define CFG_UL_SEQUENCE_TABLE_ERROR_EN_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define CFG_DL_CC_UPDATE_TRIGGERED_ADDR 0x18 /* 24 */
#define CFG_DL_CC_UPDATE_TRIGGERED_MASK 0x1 /* 1 */
#define CFG_DL_CC_UPDATE_TRIGGERED_OFFSET 0x0 /* 0 */
#define CFG_DL_CC_UPDATE_TRIGGERED_WIDTH 0x1 /* 1 */
#define CFG_DL_CC_UPDATE_TRIGGERED_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define CFG_DL_SEQUENCE_ERROR_ADDR 0x18 /* 24 */
#define CFG_DL_SEQUENCE_ERROR_MASK 0x2 /* 2 */
#define CFG_DL_SEQUENCE_ERROR_OFFSET 0x1 /* 1 */
#define CFG_DL_SEQUENCE_ERROR_WIDTH 0x1 /* 1 */
#define CFG_DL_SEQUENCE_ERROR_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define CFG_DL_SEQUENCE_TABLE_ERROR_ADDR 0x18 /* 24 */
#define CFG_DL_SEQUENCE_TABLE_ERROR_MASK 0x4 /* 4 */
#define CFG_DL_SEQUENCE_TABLE_ERROR_OFFSET 0x2 /* 2 */
#define CFG_DL_SEQUENCE_TABLE_ERROR_WIDTH 0x1 /* 1 */
#define CFG_DL_SEQUENCE_TABLE_ERROR_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define CFG_UL_CC_UPDATE_TRIGGERED_ADDR 0x18 /* 24 */
#define CFG_UL_CC_UPDATE_TRIGGERED_MASK 0x100 /* 256 */
#define CFG_UL_CC_UPDATE_TRIGGERED_OFFSET 0x8 /* 8 */
#define CFG_UL_CC_UPDATE_TRIGGERED_WIDTH 0x1 /* 1 */
#define CFG_UL_CC_UPDATE_TRIGGERED_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define CFG_UL_SEQUENCE_ERROR_ADDR 0x18 /* 24 */
#define CFG_UL_SEQUENCE_ERROR_MASK 0x200 /* 512 */
#define CFG_UL_SEQUENCE_ERROR_OFFSET 0x9 /* 9 */
#define CFG_UL_SEQUENCE_ERROR_WIDTH 0x1 /* 1 */
#define CFG_UL_SEQUENCE_ERROR_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define CFG_UL_SEQUENCE_TABLE_ERROR_ADDR 0x18 /* 24 */
#define CFG_UL_SEQUENCE_TABLE_ERROR_MASK 0x400 /* 1024 */
#define CFG_UL_SEQUENCE_TABLE_ERROR_OFFSET 0xa /* 10 */
#define CFG_UL_SEQUENCE_TABLE_ERROR_WIDTH 0x1 /* 1 */
#define CFG_UL_SEQUENCE_TABLE_ERROR_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CFG_MONITOR_SELECT_READ_ADDR 0x104 /* 260 */
#define CFG_MONITOR_SELECT_READ_MASK 0x3f /* 63 */
#define CFG_MONITOR_SELECT_READ_OFFSET 0x0 /* 0 */
#define CFG_MONITOR_SELECT_READ_WIDTH 0x6 /* 6 */
#define CFG_MONITOR_SELECT_READ_DEFAULT 0x0 /* 0 */

/* Type = wPlsH  */
#define CFG_MONITOR_SNAPSHOT_ADDR 0x108 /* 264 */
#define CFG_MONITOR_SNAPSHOT_MASK 0x1 /* 1 */
#define CFG_MONITOR_SNAPSHOT_OFFSET 0x0 /* 0 */
#define CFG_MONITOR_SNAPSHOT_WIDTH 0x1 /* 1 */
#define CFG_MONITOR_SNAPSHOT_DEFAULT 0x0 /* 0 */

/* Type = wPlsH  */
#define CFG_MONITOR_SAMPLE_ADDR 0x10c /* 268 */
#define CFG_MONITOR_SAMPLE_MASK 0x1 /* 1 */
#define CFG_MONITOR_SAMPLE_OFFSET 0x0 /* 0 */
#define CFG_MONITOR_SAMPLE_WIDTH 0x1 /* 1 */
#define CFG_MONITOR_SAMPLE_DEFAULT 0x0 /* 0 */

/* Type = wPlsH  */
#define CFG_MONITOR_CLEAR_ADDR 0x110 /* 272 */
#define CFG_MONITOR_CLEAR_MASK 0x1 /* 1 */
#define CFG_MONITOR_CLEAR_OFFSET 0x0 /* 0 */
#define CFG_MONITOR_CLEAR_WIDTH 0x1 /* 1 */
#define CFG_MONITOR_CLEAR_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define CFG_MONITOR_READ_31__0_ADDR 0x120 /* 288 */
#define CFG_MONITOR_READ_31__0_MASK 0xffffffff /* 4294967295 */
#define CFG_MONITOR_READ_31__0_OFFSET 0x0 /* 0 */
#define CFG_MONITOR_READ_31__0_WIDTH 0x20 /* 32 */
#define CFG_MONITOR_READ_31__0_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define CFG_MONITOR_READ_63_32_ADDR 0x124 /* 292 */
#define CFG_MONITOR_READ_63_32_MASK 0xffffffff /* 4294967295 */
#define CFG_MONITOR_READ_63_32_OFFSET 0x0 /* 0 */
#define CFG_MONITOR_READ_63_32_WIDTH 0x20 /* 32 */
#define CFG_MONITOR_READ_63_32_DEFAULT 0x0 /* 0 */


/*-----------------------------------------------------------------------------
* C Header bank register definitions for bank chan_proc_fram 
* with prefix fram_ @ address 0x2000
*------------------------------------------------------------------------------
*/
/* Type = rwpdef  */
#define FRAM_CHANP_DL_DISABLE_ADDR 0x2000 /* 8192 */
#define FRAM_CHANP_DL_DISABLE_MASK 0x1 /* 1 */
#define FRAM_CHANP_DL_DISABLE_OFFSET 0x0 /* 0 */
#define FRAM_CHANP_DL_DISABLE_WIDTH 0x1 /* 1 */
#define FRAM_CHANP_DL_DISABLE_DEFAULT 0x1 /* 1 */

/* Type = roSig  */
#define FRAM_CHANP_DL_READY_ADDR 0x2000 /* 8192 */
#define FRAM_CHANP_DL_READY_MASK 0x2 /* 2 */
#define FRAM_CHANP_DL_READY_OFFSET 0x1 /* 1 */
#define FRAM_CHANP_DL_READY_WIDTH 0x1 /* 1 */
#define FRAM_CHANP_DL_READY_DEFAULT 0x0 /* 0 */

/* Type = rwpdef  */
#define FRAM_CHANP_UL_DISABLE_ADDR 0x2000 /* 8192 */
#define FRAM_CHANP_UL_DISABLE_MASK 0x4 /* 4 */
#define FRAM_CHANP_UL_DISABLE_OFFSET 0x2 /* 2 */
#define FRAM_CHANP_UL_DISABLE_WIDTH 0x1 /* 1 */
#define FRAM_CHANP_UL_DISABLE_DEFAULT 0x1 /* 1 */

/* Type = roSig  */
#define FRAM_CHANP_UL_READY_ADDR 0x2000 /* 8192 */
#define FRAM_CHANP_UL_READY_MASK 0x8 /* 8 */
#define FRAM_CHANP_UL_READY_OFFSET 0x3 /* 3 */
#define FRAM_CHANP_UL_READY_WIDTH 0x1 /* 1 */
#define FRAM_CHANP_UL_READY_DEFAULT 0x0 /* 0 */


/*-----------------------------------------------------------------------------
* C Header bank register definitions for bank chan_proc_setup 
* with prefix ctrl_ @ address 0x4000
*------------------------------------------------------------------------------
*/
/* Type = rwpdef  */
#define CTRL_DL_NUMBER_OF_ANTENNAS_ADDR 0x4004 /* 16388 */
#define CTRL_DL_NUMBER_OF_ANTENNAS_MASK 0xf /* 15 */
#define CTRL_DL_NUMBER_OF_ANTENNAS_OFFSET 0x0 /* 0 */
#define CTRL_DL_NUMBER_OF_ANTENNAS_WIDTH 0x4 /* 4 */
#define CTRL_DL_NUMBER_OF_ANTENNAS_DEFAULT 0x0 /* 0 */

/* Type = rwpdef  */
#define CTRL_DL_ANTENNA_INTERLEAVE_ADDR 0x4008 /* 16392 */
#define CTRL_DL_ANTENNA_INTERLEAVE_MASK 0x7 /* 7 */
#define CTRL_DL_ANTENNA_INTERLEAVE_OFFSET 0x0 /* 0 */
#define CTRL_DL_ANTENNA_INTERLEAVE_WIDTH 0x3 /* 3 */
#define CTRL_DL_ANTENNA_INTERLEAVE_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CTRL_DL_SEQUENCE_TABLE_UPDATE_MODE_ADDR 0x400c /* 16396 */
#define CTRL_DL_SEQUENCE_TABLE_UPDATE_MODE_MASK 0x1 /* 1 */
#define CTRL_DL_SEQUENCE_TABLE_UPDATE_MODE_OFFSET 0x0 /* 0 */
#define CTRL_DL_SEQUENCE_TABLE_UPDATE_MODE_WIDTH 0x1 /* 1 */
#define CTRL_DL_SEQUENCE_TABLE_UPDATE_MODE_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CTRL_DL_SEQUENCE_TABLE_CC_SEL_ADDR 0x400c /* 16396 */
#define CTRL_DL_SEQUENCE_TABLE_CC_SEL_MASK 0xf0 /* 240 */
#define CTRL_DL_SEQUENCE_TABLE_CC_SEL_OFFSET 0x4 /* 4 */
#define CTRL_DL_SEQUENCE_TABLE_CC_SEL_WIDTH 0x4 /* 4 */
#define CTRL_DL_SEQUENCE_TABLE_CC_SEL_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CTRL_DL_SEQUENCE_TABLE_ENABLE_ADDR 0x400c /* 16396 */
#define CTRL_DL_SEQUENCE_TABLE_ENABLE_MASK 0x40000000 /* 1073741824 */
#define CTRL_DL_SEQUENCE_TABLE_ENABLE_OFFSET 0x1e /* 30 */
#define CTRL_DL_SEQUENCE_TABLE_ENABLE_WIDTH 0x1 /* 1 */
#define CTRL_DL_SEQUENCE_TABLE_ENABLE_DEFAULT 0x0 /* 0 */

/* Type = wPlsH  */
#define CTRL_DL_SEQUENCE_TABLE_WR_STROBE_ADDR 0x400c /* 16396 */
#define CTRL_DL_SEQUENCE_TABLE_WR_STROBE_MASK 0x80000000 /* 2147483648 */
#define CTRL_DL_SEQUENCE_TABLE_WR_STROBE_OFFSET 0x1f /* 31 */
#define CTRL_DL_SEQUENCE_TABLE_WR_STROBE_WIDTH 0x1 /* 1 */
#define CTRL_DL_SEQUENCE_TABLE_WR_STROBE_DEFAULT 0x0 /* 0 */

/* Type = rwpdef  repeats using MAX_NUM_CC @ multiples of 0x010 */
#define CTRL_NEXT_DL_CC_NUMBER_OF_RES_ADDR 0x4010 /* 16400 */
#define CTRL_NEXT_DL_CC_NUMBER_OF_RES_MASK 0x1fff /* 8191 */
#define CTRL_NEXT_DL_CC_NUMBER_OF_RES_OFFSET 0x0 /* 0 */
#define CTRL_NEXT_DL_CC_NUMBER_OF_RES_WIDTH 0xd /* 13 */
#define CTRL_NEXT_DL_CC_NUMBER_OF_RES_DEFAULT 0x0 /* 0 */

/* Type = roSig  repeats using MAX_NUM_CC @ multiples of 0x010 */
#define CTRL_CURRENT_DL_CC_NUMBER_OF_RES_ADDR 0x4014 /* 16404 */
#define CTRL_CURRENT_DL_CC_NUMBER_OF_RES_MASK 0x1fff /* 8191 */
#define CTRL_CURRENT_DL_CC_NUMBER_OF_RES_OFFSET 0x0 /* 0 */
#define CTRL_CURRENT_DL_CC_NUMBER_OF_RES_WIDTH 0xd /* 13 */
#define CTRL_CURRENT_DL_CC_NUMBER_OF_RES_DEFAULT 0x0 /* 0 */

/* Type = rwpdef  */
#define CTRL_UL_NUMBER_OF_ANTENNAS_ADDR 0x4204 /* 16900 */
#define CTRL_UL_NUMBER_OF_ANTENNAS_MASK 0xf /* 15 */
#define CTRL_UL_NUMBER_OF_ANTENNAS_OFFSET 0x0 /* 0 */
#define CTRL_UL_NUMBER_OF_ANTENNAS_WIDTH 0x4 /* 4 */
#define CTRL_UL_NUMBER_OF_ANTENNAS_DEFAULT 0x0 /* 0 */

/* Type = rwpdef  */
#define CTRL_UL_ANTENNA_INTERLEAVE_ADDR 0x4208 /* 16904 */
#define CTRL_UL_ANTENNA_INTERLEAVE_MASK 0x7 /* 7 */
#define CTRL_UL_ANTENNA_INTERLEAVE_OFFSET 0x0 /* 0 */
#define CTRL_UL_ANTENNA_INTERLEAVE_WIDTH 0x3 /* 3 */
#define CTRL_UL_ANTENNA_INTERLEAVE_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CTRL_UL_SEQUENCE_TABLE_UPDATE_MODE_ADDR 0x420c /* 16908 */
#define CTRL_UL_SEQUENCE_TABLE_UPDATE_MODE_MASK 0x1 /* 1 */
#define CTRL_UL_SEQUENCE_TABLE_UPDATE_MODE_OFFSET 0x0 /* 0 */
#define CTRL_UL_SEQUENCE_TABLE_UPDATE_MODE_WIDTH 0x1 /* 1 */
#define CTRL_UL_SEQUENCE_TABLE_UPDATE_MODE_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CTRL_UL_SEQUENCE_TABLE_CC_SEL_ADDR 0x420c /* 16908 */
#define CTRL_UL_SEQUENCE_TABLE_CC_SEL_MASK 0xf0 /* 240 */
#define CTRL_UL_SEQUENCE_TABLE_CC_SEL_OFFSET 0x4 /* 4 */
#define CTRL_UL_SEQUENCE_TABLE_CC_SEL_WIDTH 0x4 /* 4 */
#define CTRL_UL_SEQUENCE_TABLE_CC_SEL_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define CTRL_UL_SEQUENCE_TABLE_ENABLE_ADDR 0x420c /* 16908 */
#define CTRL_UL_SEQUENCE_TABLE_ENABLE_MASK 0x40000000 /* 1073741824 */
#define CTRL_UL_SEQUENCE_TABLE_ENABLE_OFFSET 0x1e /* 30 */
#define CTRL_UL_SEQUENCE_TABLE_ENABLE_WIDTH 0x1 /* 1 */
#define CTRL_UL_SEQUENCE_TABLE_ENABLE_DEFAULT 0x0 /* 0 */

/* Type = wPlsH  */
#define CTRL_UL_SEQUENCE_TABLE_WR_STROBE_ADDR 0x420c /* 16908 */
#define CTRL_UL_SEQUENCE_TABLE_WR_STROBE_MASK 0x80000000 /* 2147483648 */
#define CTRL_UL_SEQUENCE_TABLE_WR_STROBE_OFFSET 0x1f /* 31 */
#define CTRL_UL_SEQUENCE_TABLE_WR_STROBE_WIDTH 0x1 /* 1 */
#define CTRL_UL_SEQUENCE_TABLE_WR_STROBE_DEFAULT 0x0 /* 0 */

/* Type = rwpdef  repeats using MAX_NUM_CC @ multiples of 0x010 */
#define CTRL_NEXT_UL_CC_NUMBER_OF_RES_ADDR 0x4210 /* 16912 */
#define CTRL_NEXT_UL_CC_NUMBER_OF_RES_MASK 0x1fff /* 8191 */
#define CTRL_NEXT_UL_CC_NUMBER_OF_RES_OFFSET 0x0 /* 0 */
#define CTRL_NEXT_UL_CC_NUMBER_OF_RES_WIDTH 0xd /* 13 */
#define CTRL_NEXT_UL_CC_NUMBER_OF_RES_DEFAULT 0x0 /* 0 */

/* Type = roSig  repeats using MAX_NUM_CC @ multiples of 0x010 */
#define CTRL_CURRENT_UL_CC_NUMBER_OF_RES_ADDR 0x4214 /* 16916 */
#define CTRL_CURRENT_UL_CC_NUMBER_OF_RES_MASK 0x1fff /* 8191 */
#define CTRL_CURRENT_UL_CC_NUMBER_OF_RES_OFFSET 0x0 /* 0 */
#define CTRL_CURRENT_UL_CC_NUMBER_OF_RES_WIDTH 0xd /* 13 */
#define CTRL_CURRENT_UL_CC_NUMBER_OF_RES_DEFAULT 0x0 /* 0 */


/*-----------------------------------------------------------------------------
* C Header bank register definitions for bank chan_proc_sequence_table 
* with prefix sequence_tab_ @ address 0x6000
*------------------------------------------------------------------------------
*/
/* Type = rw  */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_NUM_RES_ADDR 0x6000 /* 24576 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_NUM_RES_MASK 0xfff /* 4095 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_NUM_RES_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_NUM_RES_WIDTH 0xc /* 12 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_NUM_RES_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_RE_START_ADDR 0x6000 /* 24576 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_RE_START_MASK 0xfff0000 /* 268369920 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_RE_START_OFFSET 0x10 /* 16 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_RE_START_WIDTH 0xc /* 12 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_RE_START_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_CC_ID_ADDR 0x6004 /* 24580 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_CC_ID_MASK 0xf /* 15 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_CC_ID_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_CC_ID_WIDTH 0x4 /* 4 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_CC_ID_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_CC_NUM_ADDR 0x6004 /* 24580 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_CC_NUM_MASK 0xf00 /* 3840 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_CC_NUM_OFFSET 0x8 /* 8 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_CC_NUM_WIDTH 0x4 /* 4 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_CC_NUM_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_FINAL_ADDR 0x6004 /* 24580 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_FINAL_MASK 0x40000000 /* 1073741824 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_FINAL_OFFSET 0x1e /* 30 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_FINAL_WIDTH 0x1 /* 1 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_FINAL_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_LAST_ADDR 0x6004 /* 24580 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_LAST_MASK 0x80000000 /* 2147483648 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_LAST_OFFSET 0x1f /* 31 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_LAST_WIDTH 0x1 /* 1 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_LAST_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_ANT_CONFIG_ADDR 0x6008 /* 24584 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_ANT_CONFIG_MASK 0xffffffff /* 4294967295 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_ANT_CONFIG_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_ANT_CONFIG_WIDTH 0x20 /* 32 */
#define SEQUENCE_TAB_NEXT_DL_CC_CONFIGURATION_ANT_CONFIG_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_NUM_RES_ADDR 0x6400 /* 25600 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_NUM_RES_MASK 0xfff /* 4095 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_NUM_RES_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_NUM_RES_WIDTH 0xc /* 12 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_NUM_RES_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_RE_START_ADDR 0x6400 /* 25600 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_RE_START_MASK 0xfff0000 /* 268369920 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_RE_START_OFFSET 0x10 /* 16 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_RE_START_WIDTH 0xc /* 12 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_RE_START_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_CC_ID_ADDR 0x6404 /* 25604 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_CC_ID_MASK 0xf /* 15 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_CC_ID_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_CC_ID_WIDTH 0x4 /* 4 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_CC_ID_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_CC_NUM_ADDR 0x6404 /* 25604 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_CC_NUM_MASK 0xf00 /* 3840 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_CC_NUM_OFFSET 0x8 /* 8 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_CC_NUM_WIDTH 0x4 /* 4 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_CC_NUM_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_FINAL_ADDR 0x6404 /* 25604 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_FINAL_MASK 0x40000000 /* 1073741824 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_FINAL_OFFSET 0x1e /* 30 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_FINAL_WIDTH 0x1 /* 1 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_FINAL_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_LAST_ADDR 0x6404 /* 25604 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_LAST_MASK 0x80000000 /* 2147483648 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_LAST_OFFSET 0x1f /* 31 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_LAST_WIDTH 0x1 /* 1 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_LAST_DEFAULT 0x0 /* 0 */

/* Type = rw  */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_ANT_CONFIG_ADDR 0x6408 /* 25608 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_ANT_CONFIG_MASK 0xffffffff /* 4294967295 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_ANT_CONFIG_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_ANT_CONFIG_WIDTH 0x20 /* 32 */
#define SEQUENCE_TAB_NEXT_UL_CC_CONFIGURATION_ANT_CONFIG_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_NUM_RES_ADDR 0x6800 /* 26624 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_NUM_RES_MASK 0xfff /* 4095 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_NUM_RES_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_NUM_RES_WIDTH 0xc /* 12 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_NUM_RES_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_RE_START_ADDR 0x6800 /* 26624 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_RE_START_MASK 0xfff0000 /* 268369920 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_RE_START_OFFSET 0x10 /* 16 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_RE_START_WIDTH 0xc /* 12 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_RE_START_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_CC_ID_ADDR 0x6804 /* 26628 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_CC_ID_MASK 0xf /* 15 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_CC_ID_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_CC_ID_WIDTH 0x4 /* 4 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_CC_ID_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_CC_NUM_ADDR 0x6804 /* 26628 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_CC_NUM_MASK 0xf00 /* 3840 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_CC_NUM_OFFSET 0x8 /* 8 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_CC_NUM_WIDTH 0x4 /* 4 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_CC_NUM_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_FINAL_ADDR 0x6804 /* 26628 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_FINAL_MASK 0x40000000 /* 1073741824 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_FINAL_OFFSET 0x1e /* 30 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_FINAL_WIDTH 0x1 /* 1 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_FINAL_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_LAST_ADDR 0x6804 /* 26628 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_LAST_MASK 0x80000000 /* 2147483648 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_LAST_OFFSET 0x1f /* 31 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_LAST_WIDTH 0x1 /* 1 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_LAST_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_ANT_CONFIG_ADDR 0x6808 /* 26632 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_ANT_CONFIG_MASK 0xffffffff /* 4294967295 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_ANT_CONFIG_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_ANT_CONFIG_WIDTH 0x20 /* 32 */
#define SEQUENCE_TAB_CURRENT_DL_CC_CONFIGURATION_ANT_CONFIG_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_NUM_RES_ADDR 0x6c00 /* 27648 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_NUM_RES_MASK 0xfff /* 4095 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_NUM_RES_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_NUM_RES_WIDTH 0xc /* 12 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_NUM_RES_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_RE_START_ADDR 0x6c00 /* 27648 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_RE_START_MASK 0xfff0000 /* 268369920 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_RE_START_OFFSET 0x10 /* 16 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_RE_START_WIDTH 0xc /* 12 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_RE_START_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_CC_ID_ADDR 0x6c04 /* 27652 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_CC_ID_MASK 0xf /* 15 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_CC_ID_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_CC_ID_WIDTH 0x4 /* 4 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_CC_ID_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_CC_NUM_ADDR 0x6c04 /* 27652 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_CC_NUM_MASK 0xf00 /* 3840 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_CC_NUM_OFFSET 0x8 /* 8 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_CC_NUM_WIDTH 0x4 /* 4 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_CC_NUM_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_FINAL_ADDR 0x6c04 /* 27652 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_FINAL_MASK 0x40000000 /* 1073741824 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_FINAL_OFFSET 0x1e /* 30 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_FINAL_WIDTH 0x1 /* 1 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_FINAL_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_LAST_ADDR 0x6c04 /* 27652 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_LAST_MASK 0x80000000 /* 2147483648 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_LAST_OFFSET 0x1f /* 31 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_LAST_WIDTH 0x1 /* 1 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_LAST_DEFAULT 0x0 /* 0 */

/* Type = roSig  */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_ANT_CONFIG_ADDR 0x6c08 /* 27656 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_ANT_CONFIG_MASK 0xffffffff /* 4294967295 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_ANT_CONFIG_OFFSET 0x0 /* 0 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_ANT_CONFIG_WIDTH 0x20 /* 32 */
#define SEQUENCE_TAB_CURRENT_UL_CC_CONFIGURATION_ANT_CONFIG_DEFAULT 0x0 /* 0 */


