all: libxorif libxobf xorif-app

libxorif:
	doxygen libxorif_config.dox

libxobf:
	doxygen libxobf_config.dox

xorif-app:
	doxygen xorif_app_config.dox

clean:
	rm -rf libxorif_html
	rm -rf libxobf_html
	rm -rf xorif_app_html
