all: libxorif xorif-app libxocp

libxorif:
	doxygen libxorif_config.dox

xorif-app:
	doxygen xorif_app_config.dox

libxocp:
	doxygen libxocp_config.dox

clean:
	rm -rf libxorif_html
	rm -rf xorif_app_html

