## YAML Configuration file

cfg:
  
  ## ---------------------------------------------------------------------------
  ## IP Configurations. These are some basic examples used by Xilinx. These can 
  ## be extended by the user.
  ## This can be useful if you want to check resource utilisation on multiple 
  ## configurations for example.
  ## ---------------------------------------------------------------------------
  ip:

    ## -------------------------------------------------------------------------
    ## SW development configuration. This is a good example of a more complex 
    ## configuration. AMD use this for Driver testing.
    ## Formally known as om5_10_swtest:
    ## -------------------------------------------------------------------------
    e4x8000x10_ss8x8_cc4x6600_dcc16x4x4x12x8_swtest:
      CONFIG.Physical_Ethernet_Rate    : "10G"
      CONFIG.Axis_Ports_Fram           : 8
      CONFIG.Axis_Ports_Defm           : 8
      CONFIG.Physical_Ethernet_Ports   : 4
      CONFIG.Xran_Max_Comp_Carr        : 4
      CONFIG.Xran_Max_Dl_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Ul_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Dl_Data_1kWords  : 16
      CONFIG.Xran_Max_Scs              : 6600
      CONFIG.Xran_Max_Dl_Data_Pointers : 12
      CONFIG.Xran_Max_Ctrl_Symbols     : 8
      CONFIG.Fram_Eth_Pkt_Max          : 8000
      CONFIG.Defm_Eth_Pkt_Max          : 8000
      CONFIG.Circ_Meta_Table_Depth     : 256
      CONFIG.Exdes_TorwaveDepth        : 122880
      
    e4x8000x10_ss4x4_cc4x6600_dcc16x4x4x12x8_swtest:
      CONFIG.Physical_Ethernet_Rate    : "10G"
      CONFIG.Axis_Ports_Fram           : 4
      CONFIG.Axis_Ports_Defm           : 4
      CONFIG.Physical_Ethernet_Ports   : 4
      CONFIG.Xran_Max_Comp_Carr        : 4
      CONFIG.Xran_Max_Dl_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Ul_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Dl_Data_1kWords  : 16
      CONFIG.Xran_Max_Scs              : 6600
      CONFIG.Xran_Max_Dl_Data_Pointers : 12
      CONFIG.Xran_Max_Ctrl_Symbols     : 8
      CONFIG.Fram_Eth_Pkt_Max          : 8000
      CONFIG.Defm_Eth_Pkt_Max          : 8000
      CONFIG.Circ_Meta_Table_Depth     : 256
      CONFIG.Exdes_TorwaveDepth        : 122880

    e4x8000x25_ss4x4_cc4x6600_dcc16x4x4x12x8_swtest:
      CONFIG.Physical_Ethernet_Rate    : "25G"
      CONFIG.Axis_Ports_Fram           : 4
      CONFIG.Axis_Ports_Defm           : 4
      CONFIG.Physical_Ethernet_Ports   : 4
      CONFIG.Xran_Max_Comp_Carr        : 4
      CONFIG.Xran_Max_Dl_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Ul_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Dl_Data_1kWords  : 16
      CONFIG.Xran_Max_Scs              : 6600
      CONFIG.Xran_Max_Dl_Data_Pointers : 12
      CONFIG.Xran_Max_Ctrl_Symbols     : 8
      CONFIG.Fram_Eth_Pkt_Max          : 8000
      CONFIG.Defm_Eth_Pkt_Max          : 8000
      CONFIG.Circ_Meta_Table_Depth     : 256
      CONFIG.Exdes_TorwaveDepth        : 122880
    
    ## -------------------------------------------------------------------------
    ## SingleEthConfigs
    ## -------------------------------------------------------------------------
    e1x9000x25_ss8x4_cc4x6600_dcc16x4x4x16x16_cmw00i_aptw262144:
      CONFIG.Physical_Ethernet_Rate    : "25G"
      CONFIG.Axis_Ports_Fram           : 4
      CONFIG.Axis_Ports_Defm           : 8
      CONFIG.Xran_Max_Dl_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Ul_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Dl_Data_1kWords  : 16
      CONFIG.Xran_Max_Dl_Data_Pointers : 16
      CONFIG.Xran_Max_Ctrl_Symbols     : 16
      CONFIG.Fram_Eth_Pkt_Max          : 9000
      CONFIG.Defm_Eth_Pkt_Max          : 9000
      CONFIG.Xran_Max_Comp_Carr        : 4
      CONFIG.Xran_Max_Scs              : 6600
      CONFIG.Circ_Meta_Table_Depth     : 256
      ##
      CONFIG.Fram_Comp_In_Core         : 1
      CONFIG.Defm_Decomp_In_Core       : 1   
      ##
      CONFIG.Exdes_TorwaveDepth        : 262144
      
    e1x9000x25_ss8x4_cc4x6600_dcc16x4x4x16x16_aptw262144:
      CONFIG.Physical_Ethernet_Rate    : "25G"
      CONFIG.Axis_Ports_Fram           : 4
      CONFIG.Axis_Ports_Defm           : 8
      CONFIG.Xran_Max_Dl_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Ul_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Dl_Data_1kWords  : 16
      CONFIG.Xran_Max_Dl_Data_Pointers : 16
      CONFIG.Xran_Max_Ctrl_Symbols     : 16
      CONFIG.Fram_Eth_Pkt_Max          : 9000
      CONFIG.Defm_Eth_Pkt_Max          : 9000
      CONFIG.Xran_Max_Comp_Carr        : 4
      CONFIG.Xran_Max_Scs              : 6600
      CONFIG.Circ_Meta_Table_Depth     : 256
      ##
      CONFIG.Exdes_TorwaveDepth        : 262144

    ## -------------------------------------------------------------------------
    ## OCP Designs
    ## -------------------------------------------------------------------------
    e1x9000x10_ss8x8_cc4x6600_dcc12x4x4x16x8_ocpi:
      CONFIG.Physical_Ethernet_Rate    : "10G"
      CONFIG.Axis_Ports_Fram           : 8
      CONFIG.Axis_Ports_Defm           : 8
      CONFIG.Xran_Max_Dl_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Ul_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Dl_Data_1kWords  : 12
      CONFIG.Xran_Max_Dl_Data_Pointers : 16
      CONFIG.Xran_Max_Ctrl_Symbols     : 8
      CONFIG.Fram_Eth_Pkt_Max          : 9000
      CONFIG.Defm_Eth_Pkt_Max          : 9000
      CONFIG.Xran_Max_Comp_Carr        : 4
      CONFIG.Xran_Max_Scs              : 6600
      CONFIG.Circ_Meta_Table_Depth     : 256
      CONFIG.Exdes_TorwaveDepth        : 122880
      CONFIG.Use_OCP_In_IP             : 1

    e1x9000x25_ss8x8_cc4x6600_dcc12x4x4x16x8_ocpi:
      CONFIG.Physical_Ethernet_Rate    : "25G"
      CONFIG.Axis_Ports_Fram           : 8
      CONFIG.Axis_Ports_Defm           : 8
      CONFIG.Xran_Max_Dl_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Ul_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Dl_Data_1kWords  : 12
      CONFIG.Xran_Max_Dl_Data_Pointers : 16
      CONFIG.Xran_Max_Ctrl_Symbols     : 8
      CONFIG.Fram_Eth_Pkt_Max          : 9000
      CONFIG.Defm_Eth_Pkt_Max          : 9000
      CONFIG.Xran_Max_Comp_Carr        : 4
      CONFIG.Xran_Max_Scs              : 6600
      CONFIG.Circ_Meta_Table_Depth     : 256
      CONFIG.Use_OCP_In_IP             : 1
      CONFIG.Exdes_TorwaveDepth        : 122880

    e1x9000x25_ss8x8_cc4x6600_dcc12x4x4x16x8_ocpi_opt:
      CONFIG.Physical_Ethernet_Rate    : "25G"
      CONFIG.Axis_Ports_Fram           : 8
      CONFIG.Axis_Ports_Defm           : 8
      CONFIG.Xran_Max_Dl_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Ul_Ctrl_1kWords  : 4
      CONFIG.Xran_Max_Dl_Data_1kWords  : 12
      CONFIG.Xran_Max_Dl_Data_Pointers : 16
      CONFIG.Xran_Max_Ctrl_Symbols     : 8
      CONFIG.Fram_Eth_Pkt_Max          : 9000
      CONFIG.Defm_Eth_Pkt_Max          : 9000
      CONFIG.Xran_Max_Comp_Carr        : 4
      CONFIG.Xran_Max_Scs              : 6600
      CONFIG.Circ_Meta_Table_Depth     : 256
      CONFIG.Use_OCP_In_IP             : 1
      CONFIG.Core_OptEth               : "NoIp4Ip6SsbBid"
      CONFIG.Core_OptCmp               : "OnlyBFP"
      CONFIG.Core_OptExt               : "NoE3E11"
      CONFIG.Exdes_TorwaveDepth        : 122880
           
  ## ---------------------------------------------------------------------------
  ## Supported boards parts for Implementation and Petalinux Build using this 
  ## flow.
  ## ---------------------------------------------------------------------------
  boards:
    zcu111:
      PART:  "xczu28dr-ffvg1517-2-e"
      BOARD: "xilinx.com:zcu111:part0:1.2"
    zcu670:
      PART:  "xczu67dr-fsve1156-2-i"
      BOARD: "xilinx.com:zcu670:part0:2.0"
    zcu102:
      PART:  "xczu9eg-ffvb1156-2-e"
      BOARD: "xilinx.com:zcu102:part0:3.3"
    vck190:
      PART:  "xcvc1902-vsva2197-2MP-e-S"
      BOARD: "xilinx.com:vck190:part0:2.2"
            
  ## ---------------------------------------------------------------------------
  ## Flow settings
  ## ---------------------------------------------------------------------------
  flow:
    ipName: roe_framer_0
    ipType: xilinx.com:ip:oran_radio_if
    bdName: "design_1"

  ## ---------------------------------------------------------------------------
  ## Block automation settings. 
  ## ---------------------------------------------------------------------------
  bacfg:
    cust_repo_ptp:  {CONFIG: {processorSelect: ARM_Linux, ptpSelect: XilinxPtpV1, cfg_addBlFifoReset: 1 }}
    norm_repo_ptp:           {processorSelect: ARM_Linux, ptpSelect: XilinxPtpV1, cfg_addBlFifoReset: 1 }
    cust_repo    :  {CONFIG: {processorSelect: ARM_Linux,                         cfg_addBlFifoReset: 1 }}
    norm_repo    :           {processorSelect: ARM_Linux,                         cfg_addBlFifoReset: 1 }

