ORAN-RADIO-IF: Xorif-app
Xorif-app
Functions
int main (int argc, char *argv[])
int do_menu (void)
int do_file (const char *name)
int do_command (const char *format,...)
int do_socket (void)
int send_to_target (const char *request, char *response)
int send_to_host (const char *response)
int ecpri_func (int argc, char **argv, char *resp)
Detailed Description
Enumeration Type Documentation
enum error_codes
Error codes.
Enumerator
PARSER_ERRORS
(Place holder for parser errors)
LINE_SIZE_LIMIT
Line length limit exceeded.
TOKEN_COUNT_LIMIT
Token count limit exceeded.
UNKNOWN_COMMAND
Unknown command.
MALFORMED_COMMAND
Malformed command.
SYSTEM_ERRORS
(Place holder for system errors)
COMMS_ERROR
Communication error.
NO_HARDWARE
No hardware present.
SYSTEM_CMD_FAILURE
Attempt to perform system command failed.
FILE_NOT_FOUND
File not found.
SUCCESS
Success! No error!
FAILURE
Failure return code.
TERMINATE
Termination return code.
NO_RESULT
Code indicate that there was no result.
Function Documentation
int do_command (const char * format, ...)
Main entry point for the command parser / handler.
Parameters
[in] format Format
Returns
SUCCESS on success
Error code on failure
Note
This is a variadic function, which handles arguments for "vsprintf".
References send_to_host(), and SUCCESS.
Referenced by do_file(), do_socket(), and main().
int do_file (const char * name)
Entry point for file mode.
Parameters
[in] name File-name
Returns
SUCCESS on success
Error code on failure
References do_command(), FAILURE, SUCCESS, and TERMINATE.
Referenced by main().
int do_menu (void)
Entry point for menu mode.
Returns
SUCCESS on success
Error code on failure
Referenced by main().
int do_socket (void)
Entry point for socket communications (server side).
Returns
SUCCESS on success
Error code on failure
References COMMS_ERROR, do_command(), proto_ecpri_handle_incoming_msg(), and SUCCESS.
Referenced by main().
int ecpri_func (int argc, char ** argv, char * resp)
Parses the input command string and calls a handler function (if found).
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
1 if no commands tokens found.
2 if no handler found for command.
0 otherwise.
References ecpri_cmds, and ECPRI_USAGE_STR.
int main (int argc, char * argv[])
Main entry point for XORIF-APP.
Parameters
[in] argc Number of command line arguments
[in] argv Array of C-style strings containing the command line arguments
Returns
EXIT_SUCCESS on success
EXIT_FAILURE on error
References do_command(), do_file(), do_menu(), do_socket(), FAILURE, SUCCESS, TERMINATE, and xorif_register_fhi_isr().
int send_to_host (const char * response)
Utility to send response message to the host (i.e.
server -> client)
Parameters
[in] response Response string
Returns
SUCCESS on success
Error code on failure
References COMMS_ERROR, and SUCCESS.
Referenced by do_command().
int send_to_target (const char * request, char * response)
Utility to send request message to the target (i.e.
client -> server)
Parameters
[in] request Request input string
[in,out] response Response output string
Returns
SUCCESS on success
Error code on failure
References COMMS_ERROR, and SUCCESS.