ORAN-RADIO-IF: Libxorif
Libxorif
Data Structures
struct xorif_device_info
struct reg_info
Macros
#define FH_DECAP_DLY_PS 5000000
#define UL_RADIO_CH_DLY_PS 30000000
Functions
int xorif_get_state (void)
void xorif_debug (int level)
int xorif_init (const char *fh_dev_name, const char *bf_dev_name)
uint32_t xorif_get_sw_version (void)
struct xorif_caps * xorif_get_capabilities (void)
int xorif_has_front_haul_interface (void)
int xorif_has_beamformer (void)
int xorif_configure_cc (uint16_t cc)
int xorif_enable_cc (uint16_t cc)
int xorif_disable_cc (uint16_t cc)
int xorif_set_cc_config (uint16_t cc, const struct xorif_cc_config *config)
int xorif_set_cc_num_rbs (uint16_t cc, uint16_t num_rbs)
int xorif_set_cc_numerology (uint16_t cc, uint16_t numerology, uint16_t extended_cp)
int xorif_set_cc_numerology_ssb (uint16_t cc, uint16_t numerology, uint16_t extended_cp)
int xorif_set_cc_time_advance (uint16_t cc, uint32_t deskew, uint32_t advance_ul, uint32_t advance_dl)
int xorif_set_cc_dl_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
int xorif_set_cc_ul_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
int xorif_set_cc_iq_compression_ssb (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
int xorif_set_cc_bw_compression (uint16_t cc, uint16_t bit_width, enum xorif_bw_comp comp_method)
int xorif_set_cc_dl_sections_per_symbol (uint16_t cc, uint16_t num_sections)
int xorif_set_cc_ul_sections_per_symbol (uint16_t cc, uint16_t num_sections)
int xorif_set_cc_frames_per_symbol (uint16_t cc, uint16_t num_frames)
int xorif_set_cc_sections_per_symbol_ssb (uint16_t cc, uint16_t num_sections)
int xorif_set_cc_frames_per_symbol_ssb (uint16_t cc, uint16_t num_frames)
int xorif_get_cc_config (uint16_t cc, struct xorif_cc_config *ptr)
uint32_t xorif_get_fhi_hw_version (void)
uint32_t xorif_get_fhi_hw_revision (void)
uint32_t xorif_get_fhi_alarms (void)
int xorif_read_fhi_reg (const char *name, uint32_t *val)
int xorif_read_fhi_reg_offset (const char *name, uint16_t offset, uint32_t *val)
int xorif_write_fhi_reg (const char *name, uint32_t value)
int xorif_write_fhi_reg_offset (const char *name, uint16_t offset, uint32_t value)
int xorif_get_fhi_eth_stats (int port, struct xorif_fhi_eth_stats *ptr)
struct xorif_fhi_caps * xorif_get_fhi_capabilities (void)
int xorif_set_fhi_dest_mac_addr (int port, const uint8_t address[])
int xorif_set_fhi_src_mac_addr (int port, const uint8_t address[])
int xorif_set_fhi_protocol (enum xorif_transport_protocol transport, uint16_t vlan, enum xorif_ip_mode ip_mode)
int xorif_set_fhi_vlan_tag (int port, uint16_t tag)
int xorif_set_fhi_packet_filter (int port, const uint32_t filter[16], uint16_t mask[4])
int xorif_enable_fhi_interrupts (uint32_t mask)
int xorif_set_fhi_eaxc_id (uint16_t du_bits, uint16_t bs_bits, uint16_t cc_bits, uint16_t ru_bits)
int xorif_set_ru_ports (uint16_t ru_bits, uint16_t ss_bits, uint16_t mask, uint16_t user_val, uint16_t prach_val, uint16_t ssb_val)
int xorif_get_fhi_cc_alloc (uint16_t cc, struct xorif_cc_alloc *ptr)
int xorif_fhi_get_num_ul_spatial_streams (void)
int xorif_fhi_get_num_dl_spatial_streams (void)
int xorif_fhi_get_max_cc (void)
int xorif_fhi_get_num_eth_ports (void)
int xorif_fhi_get_min_numerology (void)
int xorif_fhi_get_max_numerology (void)
int xorif_fhi_get_max_dl_symbols (void)
int xorif_fhi_cc_reload (uint16_t cc)
int xorif_fhi_cc_enable (uint16_t cc)
int xorif_fhi_cc_disable (uint16_t cc)
uint16_t xorif_fhi_get_enabled_mask (void)
void xorif_fhi_set_enabled_mask (uint16_t mask)
int xorif_fhi_init_cc_symbol_pointers (uint16_t cc, uint16_t dl_data_sym_num, uint16_t dl_data_sym_start_index, uint16_t dl_ctrl_sym_num, uint16_t ul_ctrl_sym_num)
int xorif_fhi_init_cc_dl_data_offsets (uint16_t cc, uint16_t dl_data_sym_num, uint16_t dl_data_sym_start_index, uint16_t symbol_buffer_start, uint16_t symbol_buffer_size)
int xorif_fhi_init_cc_rbs (uint16_t cc, uint16_t num_rbs, uint16_t numerology, uint16_t sym_per_slot)
int xorif_fhi_init_cc_ul_section_mem (uint16_t cc, uint16_t num_ctrl_per_sym_ul, uint16_t ul_ctrl_offset, uint16_t ul_ctrl_base_offset)
int xorif_fhi_init_cc_dl_section_mem (uint16_t cc, uint16_t num_ctrl_per_sym_dl, uint16_t dl_ctrl_offset)
int xorif_fhi_init_cc_ctrl_constants (uint16_t cc, uint16_t dl_ctrl_sym_num, uint16_t num_ctrl_per_sym_dl, uint16_t ul_ctrl_sym_num, uint16_t num_ctrl_per_sym_ul)
int xorif_fhi_set_cc_dl_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_meth)
int xorif_fhi_set_cc_ul_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_meth)
int xorif_fhi_configure_time_advance_offsets (uint16_t cc, uint16_t numerology, uint16_t sym_per_slot, uint32_t advance_ul, uint32_t advance_dl)
int xorif_fhi_configure_cc (uint16_t cc)
const reg_info_t * find_register (const reg_info_t *reg_map, int num, const char *name)
uint32_t read_reg_raw (struct metal_io_region *io, const char *name, uint32_t addr)
void write_reg_raw (struct metal_io_region *io, const char *name, uint32_t addr, uint32_t value)
uint32_t read_reg (struct metal_io_region *io, const char *name, uint32_t addr, uint32_t mask, uint16_t shift, uint16_t width)
void write_reg (struct metal_io_region *io, const char *name, uint32_t addr, uint32_t mask, uint16_t shift, uint16_t width, uint32_t value)
const char * get_device_name (const char *short_name)
int get_device_property_u32 (const char *dev_name, const char *prop_name, uint32_t *value)
int add_device (struct xorif_device_info *device, const char *bus_name, const char *dev_name)
int check_numerology (uint16_t numerology, uint16_t extended_cp)
int check_iq_comp_mode (uint16_t bit_width, enum xorif_iq_comp comp_method)
int check_bw_comp_mode (uint16_t bit_width, enum xorif_bw_comp comp_method)
const char * binary_string (uint32_t value, uint16_t length)
const char * binary_mask_string (uint32_t value, uint32_t mask, uint16_t length)
Detailed Description
C Library API for the Xilinx ORAN Radio Interface (libxorif)
Macro Definition Documentation
#define DEFAULT_ADVANCE_DL 90
Default downlink time advance in microseconds.
#define DEFAULT_ADVANCE_UL 90
Default uplink time advance in microseconds.
#define DEFAULT_CTRL_PER_SYM 64
Default sections per symbol.
#define DEFAULT_CTRL_PER_SYM_SSB 5
Default sections per symbol (SSB)
#define DEFAULT_DESKEW_TIME 30
Default deskew time in microseconds.
#define DEFAULT_FRAMES_PER_SYM 15
Default Ethernet frames per symbol.
#define DEFAULT_FRAMES_PER_SYM_SSB 3
Default Ethernet frames per symbol (SSB)
#define FH_DECAP_DLY_PS 5000000
Estimate of downlink delay (in picoseconds).
See PG370.
#define MAX_NUM_CC 8
Maximum number of component carriers.
Referenced by xorif_fhi_configure_cc(), xorif_fhi_init_device(), and xorif_get_fhi_cc_alloc().
#define MAX_NUM_RBS 275
Maximum number of RBs supported per CC.
Referenced by xorif_set_cc_config(), and xorif_set_cc_num_rbs().
#define MIN_NUM_RBS 2
Minimum number of RBs supported per CC.
Referenced by xorif_set_cc_config().
#define NUM_NUMEROLOGY 5
Number of numerologies.
#define RE_PER_RB 12
Number of REs per RB.
#define READ_REG (a) read_reg(fh_device.io, #a, ADDR(a), MASK(a), SHIFT(a), WIDTH(a))
Macro handles read from specified register field.
Referenced by xorif_fhi_cc_disable(), xorif_fhi_cc_enable(), xorif_fhi_get_enabled_mask(), xorif_fhi_init_device(), xorif_get_fhi_hw_revision(), and xorif_get_fhi_hw_version().
#define READ_REG_OFFSET (a, o) read_reg(fh_device.io, #a, ADDR(a) + (o), MASK(a), SHIFT(a), WIDTH(a))
Macro handles read from specified register field (address + offset).
Referenced by xorif_get_fhi_eth_stats().
#define READ_REG_RAW (a) read_reg_raw(fh_device.io, #a, a)
Macro handles raw read from specified register address.
#define SSB_NUM_RBS 20
Number of RBs for SSB.
Referenced by xorif_set_cc_config().
#define UL_RADIO_CH_DLY_PS 30000000
Estimate of uplink delay (in picoseconds).
See PG370.
#define WRITE_REG (a, v) write_reg(fh_device.io, #a, ADDR(a), MASK(a), SHIFT(a), WIDTH(a), v)
Macro handles write to specified register field.
Referenced by xorif_enable_fhi_interrupts(), xorif_fhi_cc_disable(), xorif_fhi_cc_enable(), xorif_fhi_cc_reload(), xorif_fhi_init_device(), xorif_fhi_set_enabled_mask(), xorif_get_fhi_eth_stats(), xorif_reset_fhi(), xorif_set_fhi_eaxc_id(), xorif_set_fhi_protocol(), and xorif_set_ru_ports().
#define WRITE_REG_OFFSET (a, o, v) write_reg(fh_device.io, #a, ADDR(a) + (o), MASK(a), SHIFT(a), WIDTH(a), v)
Macro handles write to specified register field (address + offset).
Referenced by xorif_fhi_configure_time_advance_offsets(), xorif_fhi_init_cc_ctrl_constants(), xorif_fhi_init_cc_dl_data_offsets(), xorif_fhi_init_cc_dl_section_mem(), xorif_fhi_init_cc_rbs(), xorif_fhi_init_cc_symbol_pointers(), xorif_fhi_init_cc_ul_section_mem(), xorif_fhi_set_cc_dl_iq_compression(), xorif_fhi_set_cc_ul_iq_compression(), xorif_set_fhi_dest_mac_addr(), xorif_set_fhi_src_mac_addr(), and xorif_set_fhi_vlan_tag().
#define WRITE_REG_RAW (a, v) write_reg_raw(fh_device.io, #a, a, v)
Macro handles raw write to specified register address.
Referenced by xorif_clear_fhi_stats(), xorif_enable_fhi_interrupts(), and xorif_fhi_init_device().
Function Documentation
int add_device (struct xorif_device_info * device, const char * bus_name, const char * dev_name)
Adds a device to libmetal framework.
Parameters
[in,out] device Pointer to structure containing device info
[in] bus_name Bus name
[in] dev_name Device name
Returns
XORIF_SUCCESS on success
XORIF_FAILURE on error
References xorif_device_info::bus_name, xorif_device_info::dev, xorif_device_info::dev_name, xorif_device_info::io, xorif_device_info::status, XORIF_FAILURE, and XORIF_SUCCESS.
Referenced by xorif_init().
const char * binary_mask_string (uint32_t value, uint32_t mask, uint16_t length)
Convert number to binary string representation, with mask.
Parameters
[in] value Input value
[in] mask Mask value
[in] length Length of input value in bits (0..32)
Returns
Pointer to c-string
Referenced by xorif_set_fhi_eaxc_id(), and xorif_set_ru_ports().
const char * binary_string (uint32_t value, uint16_t length)
Convert number to binary string representation.
Parameters
[in] value Input value
[in] length Length of input value in bits (0..32)
Returns
Pointer to c-string
int check_bw_comp_mode (uint16_t bit_width, enum xorif_bw_comp comp_method)
Checks to see if specified beamweight compression mode is supported.
Parameters
[in] bit_width Bit width (0-16)
[in] comp_method Compression method
Returns
0 if mode not supported
1 if mode is supported
References xorif_caps::bw_comp_methods.
Referenced by xorif_set_cc_bw_compression(), and xorif_set_cc_config().
int check_iq_comp_mode (uint16_t bit_width, enum xorif_iq_comp comp_method)
Checks to see if specified IQ compression mode is supported.
Parameters
[in] bit_width Bit width (0-16)
[in] comp_method Compression method
Returns
0 if mode not supported
1 if mode is supported
References xorif_caps::iq_comp_methods.
Referenced by xorif_set_cc_config(), xorif_set_cc_dl_iq_compression(), xorif_set_cc_iq_compression_ssb(), and xorif_set_cc_ul_iq_compression().
int check_numerology (uint16_t numerology, uint16_t extended_cp)
Check that the given numerology is supported.
Parameters
[in] numerology Numerology
[in] extended_cp Extended CP mode (0 = no, 1 = yes) (numerology 2 only)
Returns
0 if numerology not suported
1 if numerology supported
References xorif_caps::extended_cp, and xorif_caps::numerologies.
Referenced by xorif_set_cc_config(), xorif_set_cc_numerology(), and xorif_set_cc_numerology_ssb().
const reg_info_t * find_register (const reg_info_t * reg_map, int num, const char * name)
Find register field in register-map.
Parameters
[in] reg_map Pointer to regsiter map array
[in] num Number of elements in register map array
[in] name Name of register
Returns
Pointer to register field info (or NULL if not found)
Referenced by xorif_read_fhi_reg(), xorif_read_fhi_reg_offset(), xorif_write_fhi_reg(), and xorif_write_fhi_reg_offset().
const char * get_device_name (const char * short_name)
Get the device's full name given the short name.
Parameters
[in] short_name Device name to look for
Returns
NULL if not found
Pointer to name string
Note
The short name is something like "oran_radio_if", and the returned result, is the fully qualified name, e.g. "oran_radio_if.a0000000". The function will return with the name of the first matching device, and if multiple names match only the first gets reported. The returned pointer points to a static char buffer that owned by this function. The buffer contents are valid until the function is called again.
Referenced by xorif_init().
int get_device_property_u32 (const char * dev_name, const char * prop_name, uint32_t * value)
Get device 'u32' property from device tree file system.
Parameters
[in] dev_name Device name
[in] prop_name Property name
[in,out] value Pointer to return the read property value
Returns
0 if not found
1 if found
Referenced by xorif_fhi_init_device().
uint32_t read_reg (struct metal_io_region * io, const char * name, uint32_t addr, uint32_t mask, uint16_t shift, uint16_t width)
Utility function to read from a register field in the specified IO region.
Parameters
[in] io Pointer to the IO region structure
[in] name Register field name (used for debug)
[in] addr Address to use
[in] mask Mask to be used with the field
[in] shift Number of bits to shift the field
[in] width Width of the field
Returns
Register field value
Referenced by xorif_read_fhi_reg(), and xorif_read_fhi_reg_offset().
uint32_t read_reg_raw (struct metal_io_region * io, const char * name, uint32_t addr)
Utility function to read from an address in the specified IO region.
Parameters
[in] io Pointer to the IO region structure
[in] name Register field name (used for debug)
[in] addr Address to use
Returns
Register field value
void write_reg (struct metal_io_region * io, const char * name, uint32_t addr, uint32_t mask, uint16_t shift, uint16_t width, uint32_t value)
Utility function to write to a register field in the specified IO region.
Parameters
[in] io Pointer to the IO region structure
[in] name Register field name (used for debug)
[in] addr Address to use
[in] mask Mask to be used with the field
[in] shift Number of bits to shift the field
[in] width Width of the field
[in] value The value to write to the register
Referenced by xorif_write_fhi_reg(), and xorif_write_fhi_reg_offset().
void write_reg_raw (struct metal_io_region * io, const char * name, uint32_t addr, uint32_t value)
Utility function to write to an address in the specified IO region.
Parameters
[in] io Pointer to the IO region structure
[in] name Register field name (used for debug)
[in] addr Address to use
[in] value The value to write to the register
void xorif_clear_fhi_alarms (void)
Clear alarms for Front Haul Interface.
Referenced by xorif_reset_fhi().
void xorif_clear_fhi_stats (void)
Clear stats / counters for Front Haul Interface.
References WRITE_REG_RAW.
Referenced by xorif_reset_fhi().
int xorif_configure_cc (uint16_t cc)
Configure a component carrier.
Parameters
[in] cc Component carrier to configure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_caps::max_cc, xorif_cc_config::num_rbs, xorif_cc_config::numerology, xorif_cc_config::numerology_ssb, xorif_fhi_configure_cc(), xorif_has_beamformer(), XORIF_INVALID_CC, XORIF_INVALID_CONFIG, and XORIF_SUCCESS.
void xorif_debug (int level)
Set debug level for the library.
Parameters
[in] level Debug level (0 = no debug, 1 = minimal, 2 = verbose)
int xorif_disable_cc (uint16_t cc)
Disables the specified component carrier.
Parameters
[in] cc Component carrier to configure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_caps::max_cc, xorif_fhi_cc_disable(), and XORIF_INVALID_CC.
int xorif_enable_cc (uint16_t cc)
Enables the specified component carrier.
Parameters
[in] cc Component carrier to configure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_caps::max_cc, xorif_fhi_cc_enable(), and XORIF_INVALID_CC.
int xorif_enable_fhi_interrupts (uint32_t mask)
Enable / disable Front Haul Interface interrupts.
Parameters
[in] mask Mask (bit-map of interrupt sources)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
The mask bits are the same as in the enum xorif_fhi_alarms.
References WRITE_REG, WRITE_REG_RAW, and XORIF_SUCCESS.
int xorif_fhi_cc_disable (uint16_t cc)
Disable the component carrier.
Parameters
[in] cc Component carrier to configure
Returns
XORIF_SUCCESS
References READ_REG, WRITE_REG, and XORIF_SUCCESS.
Referenced by xorif_disable_cc().
int xorif_fhi_cc_enable (uint16_t cc)
Enable the component carrier.
Parameters
[in] cc Component carrier to configure
Returns
XORIF_SUCCESS
References READ_REG, WRITE_REG, and XORIF_SUCCESS.
Referenced by xorif_enable_cc(), and xorif_fhi_configure_cc().
int xorif_fhi_cc_reload (uint16_t cc)
Re-load / re-configure the component carrier configuration.
Parameters
[in] cc Component carrier to configure
Returns
XORIF_SUCCESS
References WRITE_REG, and XORIF_SUCCESS.
Referenced by xorif_fhi_configure_cc().
int xorif_fhi_configure_cc (uint16_t cc)
Configure the specified component carrier.
Parameters
[in] cc Component carrier to configure
Returns
XORIF_SUCCESS on success
XORIF_FAILURE on error
References xorif_cc_config::advance_dl, xorif_cc_config::advance_ul, xorif_cc_config::deskew, xorif_cc_alloc::dl_ctrl_offset, xorif_cc_alloc::dl_ctrl_offset_size, xorif_cc_alloc::dl_ctrl_sym_num, xorif_cc_alloc::dl_data_buff_size, xorif_cc_alloc::dl_data_buff_start, xorif_cc_alloc::dl_data_sym_num, xorif_cc_alloc::dl_data_sym_start, xorif_cc_config::extended_cp, xorif_cc_config::extended_cp_ssb, xorif_cc_config::iq_comp_meth_dl, xorif_cc_config::iq_comp_meth_ssb, xorif_cc_config::iq_comp_meth_ul, xorif_cc_config::iq_comp_width_dl, xorif_cc_config::iq_comp_width_ssb, xorif_cc_config::iq_comp_width_ul, xorif_fhi_caps::max_ctrl_symbols, xorif_fhi_caps::max_data_symbols, xorif_fhi_caps::max_dl_ctrl_1kwords, xorif_fhi_caps::max_dl_data_1kwords, MAX_NUM_CC, xorif_fhi_caps::max_ssb_ctrl_512words, xorif_fhi_caps::max_ssb_data_512words, xorif_fhi_caps::max_subcarriers, xorif_fhi_caps::max_ul_ctrl_1kwords, xorif_cc_config::num_ctrl_per_sym_dl, xorif_cc_config::num_ctrl_per_sym_ssb, xorif_cc_config::num_ctrl_per_sym_ul, xorif_cc_config::num_frames_per_sym, xorif_cc_config::num_frames_per_sym_ssb, xorif_cc_config::num_rbs, xorif_cc_config::num_rbs_ssb, xorif_cc_config::numerology, xorif_cc_config::numerology_ssb, xorif_cc_alloc::ssb_ctrl_offset, xorif_cc_alloc::ssb_ctrl_offset_size, xorif_cc_alloc::ssb_ctrl_sym_num, xorif_cc_alloc::ssb_data_buff_size, xorif_cc_alloc::ssb_data_buff_start, xorif_cc_alloc::ssb_data_sym_num, xorif_cc_alloc::ssb_data_sym_start, xorif_cc_alloc::ul_ctrl_base_offset, xorif_cc_alloc::ul_ctrl_base_offset_size, xorif_cc_alloc::ul_ctrl_offset, xorif_cc_alloc::ul_ctrl_offset_size, xorif_cc_alloc::ul_ctrl_sym_num, XORIF_BUFFER_SPACE_EXCEEDED, xorif_fhi_cc_enable(), xorif_fhi_cc_reload(), xorif_fhi_configure_time_advance_offsets(), xorif_fhi_init_cc_ctrl_constants(), xorif_fhi_init_cc_dl_data_offsets(), xorif_fhi_init_cc_dl_section_mem(), xorif_fhi_init_cc_rbs(), xorif_fhi_init_cc_symbol_pointers(), xorif_fhi_init_cc_ul_section_mem(), xorif_fhi_set_cc_dl_iq_compression(), xorif_fhi_set_cc_ul_iq_compression(), XORIF_MAX_CTRL_SYM_EXCEEDED, XORIF_MAX_DATA_SYM_EXCEEDED, and XORIF_SUCCESS.
Referenced by xorif_configure_cc().
int xorif_fhi_configure_time_advance_offsets (uint16_t cc, uint16_t numerology, uint16_t sym_per_slot, uint32_t advance_ul, uint32_t advance_dl)
Compute timing advance offsets for the specified component carrier.
Parameters
[in] cc Component carrier to configure
[in] numerology Numerology for the specified CC
[in] sym_per_slot Number of symbols per slot (0 = 14 symbols, 1 = 12 symbols)
[in] advance_ul Timing advance for uplink (equivalent to T2A_MIN_CP_UL)
[in] advance_dl Timing advance for downlink (equivalent to TCP_ADV_DL)
Returns
XORIF_SUCCESS on success
XORIF_FAILURE on error
References WRITE_REG_OFFSET, and XORIF_SUCCESS.
Referenced by xorif_fhi_configure_cc().
uint16_t xorif_fhi_get_enabled_mask (void)
Get the "enabled" component carrier bit-map mask.
Returns
Bit-map of enabled component carriers
References READ_REG.
int xorif_fhi_get_max_cc (void)
Returns the number of supported component carriers.
Returns
Number of supported component carriers
References xorif_fhi_caps::max_cc.
Referenced by xorif_get_cc_config(), xorif_get_fhi_cc_alloc(), xorif_set_cc_bw_compression(), xorif_set_cc_dl_iq_compression(), xorif_set_cc_dl_sections_per_symbol(), xorif_set_cc_frames_per_symbol(), xorif_set_cc_frames_per_symbol_ssb(), xorif_set_cc_iq_compression_ssb(), xorif_set_cc_sections_per_symbol_ssb(), xorif_set_cc_time_advance(), xorif_set_cc_ul_iq_compression(), and xorif_set_cc_ul_sections_per_symbol().
int xorif_fhi_get_max_dl_symbols (void)
Returns the maximum number of supported number of downlink symbols.
Returns
Number of supported downlink symbols
References xorif_fhi_caps::max_data_symbols.
int xorif_fhi_get_max_numerology (void)
Returns the maximum supported numerology.
Returns
Numerology
int xorif_fhi_get_min_numerology (void)
Returns the minimum supported numerology.
Returns
Numerology
int xorif_fhi_get_num_dl_spatial_streams (void)
Returns the number of downlink spatial streams (antenna ports).
Returns
Number of spatial streams (antenna ports)
References xorif_fhi_caps::no_deframer_ss.
int xorif_fhi_get_num_eth_ports (void)
Returns the number of Ethernet ports.
Returns
The number of Ethernet ports
References xorif_fhi_caps::num_eth_ports.
Referenced by xorif_get_fhi_eth_stats(), xorif_set_fhi_dest_mac_addr(), xorif_set_fhi_packet_filter(), xorif_set_fhi_protocol(), xorif_set_fhi_src_mac_addr(), and xorif_set_fhi_vlan_tag().
int xorif_fhi_get_num_ul_spatial_streams (void)
Returns the number of uplink spatial streams (antenna ports).
Returns
Number of spatial streams (antenna ports)
References xorif_fhi_caps::no_framer_ss.
int xorif_fhi_init_cc_ctrl_constants (uint16_t cc, uint16_t dl_ctrl_sym_num, uint16_t num_ctrl_per_sym_dl, uint16_t ul_ctrl_sym_num, uint16_t num_ctrl_per_sym_ul)
Configure the control constants.
Parameters
[in] cc Component carrier to configure
[in] dl_ctrl_sym_num Number of downlink control symbols
[in] num_ctrl_per_sym_dl Number of control sections per downlink symbol
[in] ul_ctrl_sym_num Number of uplink control symbols
[in] num_ctrl_per_sym_ul Number of control sections per uplink symbol
Returns
XORIF_SUCCESS on success
XORIF_FAILURE on error
References WRITE_REG_OFFSET, and XORIF_SUCCESS.
Referenced by xorif_fhi_configure_cc().
int xorif_fhi_init_cc_dl_data_offsets (uint16_t cc, uint16_t dl_data_sym_num, uint16_t dl_data_sym_start_index, uint16_t symbol_buffer_start, uint16_t symbol_buffer_size)
Configure the data offsets for the DL data buffer.
Parameters
[in] cc Component carrier to configure
[in] dl_data_sym_num Max number of D/L data symbols for the CC
[in] dl_data_sym_start_index Index for the start of the CC
[in] symbol_buffer_start Start of the D/L data buffer
[in] symbol_buffer_size Size of buffer assigned to each symbol
Returns
XORIF_SUCCESS on success
XORIF_FAILURE on error
References WRITE_REG_OFFSET, and XORIF_SUCCESS.
Referenced by xorif_fhi_configure_cc().
int xorif_fhi_init_cc_dl_section_mem (uint16_t cc, uint16_t num_ctrl_per_sym_dl, uint16_t dl_ctrl_offset)
Configure the downlink control memories.
Parameters
[in] cc Component carrier to configure
[in] num_ctrl_per_sym_dl Number of sections per symbol
[in] dl_ctrl_offset Downlink control offset
Returns
XORIF_SUCCESS on success
XORIF_FAILURE on error
References WRITE_REG_OFFSET, and XORIF_SUCCESS.
Referenced by xorif_fhi_configure_cc().
int xorif_fhi_init_cc_rbs (uint16_t cc, uint16_t num_rbs, uint16_t numerology, uint16_t sym_per_slot)
Configure the Numerology and RB count for the CC.
Parameters
[in] cc Component carrier to configure
[in] num_rbs Number of RBS to assign to this CC (max 275)
[in] numerology Numerology to set for this CC
[in] sym_per_slot Number of symbols per slot (0 = 14 symbols, 1 = 12 symbols)
Returns
XORIF_SUCCESS on success
XORIF_FAILURE on error
References WRITE_REG_OFFSET, and XORIF_SUCCESS.
Referenced by xorif_fhi_configure_cc().
int xorif_fhi_init_cc_symbol_pointers (uint16_t cc, uint16_t dl_data_sym_num, uint16_t dl_data_sym_start_index, uint16_t dl_ctrl_sym_num, uint16_t ul_ctrl_sym_num)
Sets up the numbers of symbol buckets for each CC.
Parameters
[in] cc Component carrier to configure
[in] dl_data_sym_num Max number of D/L Data symbols for the CC
[in] dl_data_sym_start_index Index for the start of the CC
[in] dl_ctrl_sym_num Max number of D/L Ctrl symbols for the CC
[in] ul_ctrl_sym_num Max number of U/L Ctrl symbols for the CC
Returns
XORIF_SUCCESS on success
XORIF_FAILURE on error
References WRITE_REG_OFFSET, and XORIF_SUCCESS.
Referenced by xorif_fhi_configure_cc().
int xorif_fhi_init_cc_ul_section_mem (uint16_t cc, uint16_t num_ctrl_per_sym_ul, uint16_t ul_ctrl_offset, uint16_t ul_ctrl_base_offset)
Configure the uplink control memories.
Parameters
[in] cc Component carrier to configure
[in] num_ctrl_per_sym_ul Number of sections per symbol
[in] ul_ctrl_offset Uplink control offset
[in] ul_ctrl_base_offset Uplink control base offset
Returns
XORIF_SUCCESS on success
XORIF_FAILURE on error
References WRITE_REG_OFFSET, and XORIF_SUCCESS.
Referenced by xorif_fhi_configure_cc().
void xorif_fhi_init_device (void)
Perform default initialization of the device.
References xorif_fhi_caps::bs_id_limit, xorif_fhi_caps::cc_id_limit, xorif_device_info::dev, xorif_device_info::dev_name, xorif_fhi_caps::du_id_limit, get_device_property_u32(), xorif_fhi_caps::max_cc, xorif_fhi_caps::max_ctrl_symbols, xorif_fhi_caps::max_data_symbols, xorif_fhi_caps::max_deframer_ethernet_pkt, xorif_fhi_caps::max_dl_ctrl_1kwords, xorif_fhi_caps::max_dl_data_1kwords, xorif_fhi_caps::max_framer_ethernet_pkt, MAX_NUM_CC, xorif_fhi_caps::max_ssb_ctrl_512words, xorif_fhi_caps::max_ssb_data_512words, xorif_fhi_caps::max_subcarriers, xorif_fhi_caps::max_ul_ctrl_1kwords, xorif_fhi_caps::no_deframer_ss, xorif_fhi_caps::no_framer_ss, xorif_fhi_caps::num_eth_ports, xorif_fhi_caps::num_prach_ports, xorif_fhi_caps::num_unsolicited_ports, READ_REG, xorif_fhi_caps::ru_id_limit, xorif_fhi_caps::ss_id_limit, xorif_fhi_caps::timer_clk_ps, WRITE_REG, WRITE_REG_RAW, and xorif_reset_fhi().
Referenced by xorif_init().
int xorif_fhi_set_cc_dl_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_meth)
Configure the downlink IQ compression for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] bit_width Bit width
[in] comp_meth Compression method
Returns
XORIF_SUCCESS on success
Error code on failure
References WRITE_REG_OFFSET, and XORIF_SUCCESS.
Referenced by xorif_fhi_configure_cc().
int xorif_fhi_set_cc_ul_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_meth)
Configure the uplink IQ compression for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] bit_width Bit width
[in] comp_meth Compression method
Returns
XORIF_SUCCESS on success
Error code on failure
References WRITE_REG_OFFSET, and XORIF_SUCCESS.
Referenced by xorif_fhi_configure_cc().
void xorif_fhi_set_enabled_mask (uint16_t mask)
Set the "enabled" component carrier bit-map mask.
Parameters
[in] mask Bit-map of enabled component carriers
References WRITE_REG.
void xorif_finish (void)
Finalize / close the API s/w.
References xorif_device_info::dev, and xorif_device_info::dev_name.
struct xorif_caps* xorif_get_capabilities (void)
Get ORAN Radio Interface capabilities.
Returns
Pointer to capabilities structure
int xorif_get_cc_config (uint16_t cc, struct xorif_cc_config * ptr)
Get the configuration for the component carrier.
Parameters
[in] cc Component carrier to configure
[in,out] ptr Pointer to component carrier configuration structure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_fhi_get_max_cc(), XORIF_INVALID_CC, XORIF_NULL_POINTER, and XORIF_SUCCESS.
uint32_t xorif_get_fhi_alarms (void)
Get alarms for Front Haul Interface.
Returns
Bit-map of alarm status (see enum xorif_fhi_alarms)
struct xorif_fhi_caps* xorif_get_fhi_capabilities (void)
Get capabilities from Front-Haul Interface.
Returns
Pointer to capabilities structure
int xorif_get_fhi_cc_alloc (uint16_t cc, struct xorif_cc_alloc * ptr)
Retrieve the configured allocation for the specified component carrier.
Parameters
[in] cc Component carrier
[in,out] ptr Pointer to component carrier allocation structure
Returns
XORIF_SUCCESS on success
Error code on failure
References MAX_NUM_CC, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, XORIF_NULL_POINTER, and XORIF_SUCCESS.
int xorif_get_fhi_eth_stats (int port, struct xorif_fhi_eth_stats * ptr)
Get Front Haul Interface Ethernet statistics for the specified port.
Parameters
[in] port Ethernet port
[in,out] ptr Pointer to component statistics data structure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_fhi_eth_stats::offset_earliest_c_pkt, xorif_fhi_eth_stats::offset_earliest_u_pkt, xorif_fhi_eth_stats::oran_rx_bit_rate, xorif_fhi_eth_stats::oran_rx_corrupt, xorif_fhi_eth_stats::oran_rx_early, xorif_fhi_eth_stats::oran_rx_early_c, xorif_fhi_eth_stats::oran_rx_error_drop, xorif_fhi_eth_stats::oran_rx_late, xorif_fhi_eth_stats::oran_rx_late_c, xorif_fhi_eth_stats::oran_rx_on_time, xorif_fhi_eth_stats::oran_rx_on_time_c, xorif_fhi_eth_stats::oran_rx_total, xorif_fhi_eth_stats::oran_rx_total_c, xorif_fhi_eth_stats::oran_tx_total, xorif_fhi_eth_stats::oran_tx_total_c, READ_REG_OFFSET, xorif_fhi_eth_stats::total_rx_bad_fcs_cnt, xorif_fhi_eth_stats::total_rx_bad_pkt_cnt, xorif_fhi_eth_stats::total_rx_bit_rate, xorif_fhi_eth_stats::total_rx_good_pkt_cnt, WRITE_REG, XORIF_FAILURE, xorif_fhi_get_num_eth_ports(), XORIF_INVALID_ETH_PORT, and XORIF_SUCCESS.
uint32_t xorif_get_fhi_hw_revision (void)
Returns the Front Haul Interface h/w internal revision number.
Returns
Revision
References READ_REG.
uint32_t xorif_get_fhi_hw_version (void)
Returns the Front Haul Interface h/w version.
Returns
Version (major = bits[24..31], minor = bits[16..23], version = bits[8..15])
References READ_REG.
int xorif_get_state (void)
Returns the current state of the library.
Returns
0 = not operational
1 = operational
uint32_t xorif_get_sw_version (void)
Return the s/w version.
Returns
Version (major = bits[24..31], minor = bits[16..23], version = bits[8..15])
int xorif_has_beamformer (void)
Check if there is a beamformer in the system.
Returns
0 = false (no)
1 = true (yes)
Referenced by xorif_configure_cc(), and xorif_set_cc_config().
int xorif_has_front_haul_interface (void)
Check if there is a front-haul interface in the system.
Returns
0 = false (no)
1 = true (yes)
References xorif_device_info::dev, and xorif_device_info::status.
int xorif_init (const char * fh_dev_name, const char * bf_dev_name)
Initialize the API s/w.
Parameters
[in] fh_dev_name Device name of the Front Haul Interface (leave as NULL for default)
[in] bf_dev_name Device name of the Beamformer (leave as NULL for default)
Returns
XORIF_SUCCESS on success
Error code on failure
References add_device(), get_device_name(), xorif_fhi_init_device(), XORIF_LIBMETAL_ERROR, and XORIF_SUCCESS.
int xorif_read_fhi_reg (const char * name, uint32_t * val)
Utility function to read a field from the Front Haul Interface register map.
Parameters
[in] name Register field name
[in,out] val Pointer to write back the read value
Returns
XORIF_SUCCESS on success
Error code on failure
References reg_info::addr, find_register(), xorif_device_info::io, reg_info::mask, read_reg(), reg_info::shift, reg_info::width, XORIF_REGISTER_NOT_FOUND, and XORIF_SUCCESS.
int xorif_read_fhi_reg_offset (const char * name, uint16_t offset, uint32_t * val)
Utility function to read a field from the Front Haul Interface register map.
Parameters
[in] name Register field name
[in] offset Offset to be used with register (useful for repeated register banks)
[in,out] val Pointer to write back the read value
Returns
XORIF_SUCCESS on success
Error code on failure
References reg_info::addr, find_register(), xorif_device_info::io, reg_info::mask, read_reg(), reg_info::shift, reg_info::width, XORIF_REGISTER_NOT_FOUND, and XORIF_SUCCESS.
void xorif_reset_fhi (void)
Reset the Front Haul Interface.
References WRITE_REG, xorif_clear_fhi_alarms(), and xorif_clear_fhi_stats().
Referenced by xorif_fhi_init_device().
int xorif_set_cc_bw_compression (uint16_t cc, uint16_t bit_width, enum xorif_bw_comp comp_method)
Configure the beam-weight compression for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] bit_width Bit width (0-16)
[in] comp_method Compression method
Returns
XORIF_SUCCESS on success
Error code on failure
Note
For alignment with O-RAN standard, a bit_width value of 0 is equivalent to 16.
References xorif_cc_config::bw_comp_meth, xorif_cc_config::bw_comp_width, check_bw_comp_mode(), XORIF_COMP_MODE_NOT_SUPPORTED, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_config (uint16_t cc, const struct xorif_cc_config * ptr)
Set the configuration for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] ptr Pointer to configuration structure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::bw_comp_meth, xorif_cc_config::bw_comp_width, check_bw_comp_mode(), check_iq_comp_mode(), check_numerology(), xorif_cc_config::extended_cp, xorif_cc_config::extended_cp_ssb, xorif_cc_config::iq_comp_meth_dl, xorif_cc_config::iq_comp_meth_ssb, xorif_cc_config::iq_comp_meth_ul, xorif_cc_config::iq_comp_width_dl, xorif_cc_config::iq_comp_width_ssb, xorif_cc_config::iq_comp_width_ul, xorif_caps::max_cc, MAX_NUM_RBS, MIN_NUM_RBS, xorif_cc_config::num_rbs, xorif_cc_config::num_rbs_ssb, xorif_cc_config::numerology, xorif_cc_config::numerology_ssb, SSB_NUM_RBS, XORIF_COMP_MODE_NOT_SUPPORTED, xorif_has_beamformer(), XORIF_INVALID_CC, XORIF_INVALID_CONFIG, XORIF_INVALID_RBS, XORIF_NULL_POINTER, XORIF_NUMEROLOGY_NOT_SUPPORTED, and XORIF_SUCCESS.
int xorif_set_cc_dl_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
Configure the downlink IQ compression for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] bit_width Bit width (0-16)
[in] comp_method Compression method
Returns
XORIF_SUCCESS on success
Error code on failure
Note
For alignment with O-RAN standard, a bit_width value of 0 is equivalent to 16.
References check_iq_comp_mode(), xorif_cc_config::iq_comp_meth_dl, xorif_cc_config::iq_comp_width_dl, XORIF_COMP_MODE_NOT_SUPPORTED, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_dl_sections_per_symbol (uint16_t cc, uint16_t num_sections)
Configure the number of sections allowed per downlink symbol.
Parameters
[in] cc Component carrier to configure
[in] num_sections Maximmum number of sections per symbol
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::num_ctrl_per_sym_dl, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_frames_per_symbol (uint16_t cc, uint16_t num_frames)
Configure the number of Ethernet frames allowed per (downlink) symbol.
Parameters
[in] cc Component carrier to configure
[in] num_frames Maximmum number of Ethernet frames per symbol
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::num_frames_per_sym, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_frames_per_symbol_ssb (uint16_t cc, uint16_t num_frames)
Configure the number of Ethernet frames allowed per SSB symbol.
Parameters
[in] cc Component carrier to configure
[in] num_frames Maximmum number of Ethernet frames per symbol
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::num_frames_per_sym_ssb, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_iq_compression_ssb (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
Configure the SSB compression for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] bit_width Bit width (0-16)
[in] comp_method Compression method
Returns
XORIF_SUCCESS on success
Error code on failure
Note
For alignment with O-RAN standard, a bit_width value of 0 is equivalent to 16.
References check_iq_comp_mode(), xorif_cc_config::iq_comp_meth_ssb, xorif_cc_config::iq_comp_width_ssb, XORIF_COMP_MODE_NOT_SUPPORTED, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_num_rbs (uint16_t cc, uint16_t num_rbs)
Set the number of RBs for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] num_rbs Number of RBs
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_caps::max_cc, MAX_NUM_RBS, xorif_cc_config::num_rbs, XORIF_INVALID_CC, XORIF_INVALID_RBS, and XORIF_SUCCESS.
int xorif_set_cc_numerology (uint16_t cc, uint16_t numerology, uint16_t extended_cp)
Set the numerology for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] numerology Numerology
[in] extended_cp Extended CP mode (0 = no, 1 = yes) (numerology 2 only)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
This function also sets the same numerology for the SSB. If SSB requires a different numerology, then this can be specified explicitly.
References check_numerology(), xorif_cc_config::extended_cp, xorif_caps::max_cc, xorif_cc_config::numerology, XORIF_INVALID_CC, XORIF_NUMEROLOGY_NOT_SUPPORTED, and XORIF_SUCCESS.
int xorif_set_cc_numerology_ssb (uint16_t cc, uint16_t numerology, uint16_t extended_cp)
Set the numerology for the component carrier's SSB.
Parameters
[in] cc Component carrier to configure
[in] numerology Numerology
[in] extended_cp Extended CP mode (0 = no, 1 = yes) (numerology 2 only)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
This function is used to specify a numerology when different to the UL/DL numerology.
References check_numerology(), xorif_cc_config::extended_cp, xorif_cc_config::extended_cp_ssb, xorif_caps::max_cc, xorif_cc_config::numerology, xorif_cc_config::numerology_ssb, XORIF_INVALID_CC, XORIF_NUMEROLOGY_NOT_SUPPORTED, and XORIF_SUCCESS.
int xorif_set_cc_sections_per_symbol_ssb (uint16_t cc, uint16_t num_sections)
Configure the number of sections allowed per SSB symbol.
Parameters
[in] cc Component carrier to configure
[in] num_sections Maximmum number of sections per symbol
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::num_ctrl_per_sym_ssb, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_time_advance (uint16_t cc, uint32_t deskew, uint32_t advance_ul, uint32_t advance_dl)
Set the maximum deskew and control advance timing for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] deskew Maximum deskew time (in microseconds)
[in] advance_ul Maximum control advance in uplink (in microseconds)
[in] advance_dl Maximum control advance in downlink (in microseconds)
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::advance_dl, xorif_cc_config::advance_ul, xorif_cc_config::deskew, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_ul_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
Configure the uplink IQ compression for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] bit_width Bit width (0-16)
[in] comp_method Compression method
Returns
XORIF_SUCCESS on success
Error code on failure
Note
For alignment with O-RAN standard, a bit_width value of 0 is equivalent to 16.
References check_iq_comp_mode(), xorif_cc_config::iq_comp_meth_ul, xorif_cc_config::iq_comp_width_ul, XORIF_COMP_MODE_NOT_SUPPORTED, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_ul_sections_per_symbol (uint16_t cc, uint16_t num_sections)
Configure the number of sections allowed per uplink symbol.
Parameters
[in] cc Component carrier to configure
[in] num_sections Maximmum number of sections per symbol
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::num_ctrl_per_sym_ul, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_fhi_dest_mac_addr (int port, const uint8_t address[])
Set the destination ethernet MAC address for the specified port.
Parameters
[in] port Ethernet port
[in] address MAC address (6 byte array)
Returns
XORIF_SUCCESS on success
Error code on failure
References WRITE_REG_OFFSET, xorif_fhi_get_num_eth_ports(), XORIF_INVALID_ETH_PORT, and XORIF_SUCCESS.
int xorif_set_fhi_eaxc_id (uint16_t du_bits, uint16_t bs_bits, uint16_t cc_bits, uint16_t ru_bits)
Set the eAxC ID (c.f.
ecpriRtcid and ecpriPcid)
Parameters
[in] du_bits DU ID length (in bits)
[in] bs_bits BS ID length (in bits)
[in] cc_bits CC ID length (in bits)
[in] ru_bits RU ID length (in bits)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
The eAxC ID is 16 bits, and the total length of the 4 fields should equal 16. See xorif_set_ru_ports for setting the spatial stream mask/values.
References binary_mask_string(), xorif_fhi_caps::bs_id_limit, xorif_fhi_caps::cc_id_limit, xorif_fhi_caps::du_id_limit, xorif_fhi_caps::ru_id_limit, WRITE_REG, XORIF_INVALID_EAXC_ID, and XORIF_SUCCESS.
int xorif_set_fhi_packet_filter (int port, const uint32_t filter[16], uint16_t mask[4])
Set the packet filter for the specified port.
Parameters
[in] port Ethernet port
[in] filter Pointer to an array of 16 x 32-bit words
[in] mask Pointer to an array of 4 x 16-bit words
Returns
XORIF_SUCCESS on success
Error code on failure
Note
The packet filter is defined by 4 filter words each 128-bits (16 bytes) wide. In the IP core's register map, each filter word is arranged as 4 x 32-bit words. Each filter word has an associated mask register which indicates whether a specific byte of the filter is used or not (if bit[X] = 0 then byte[X] of the filter word is used; if bit[x] = 1 then byte[x] of the filter word is not used). (See pg370-oran-radio-if document for full details).
References xorif_fhi_get_num_eth_ports(), XORIF_INVALID_ETH_PORT, and XORIF_SUCCESS.
Referenced by xorif_set_fhi_protocol().
int xorif_set_fhi_protocol (enum xorif_transport_protocol transport, uint16_t vlan, enum xorif_ip_mode ip_mode)
Set the protocol and IP mode.
Parameters
[in] transport Transport protocol (eCPRI, IEEE 1914.3)
[in] vlan VLAN tagging mode (0 = no VLAN, 1 = add VLAN tag)
[in] ip_mode IP mode (Raw, IPv4, IPv6)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
In addition to configuring the protocol, this function also configures the packet filters appropriately for all the Ethernet ports. If additional configuration of the packet filter is required, then this should be done after the call to this function.
References IP_MODE_RAW, PROTOCOL_ECPRI, PROTOCOL_IEEE_1914_3, WRITE_REG, xorif_fhi_get_num_eth_ports(), xorif_set_fhi_packet_filter(), and XORIF_SUCCESS.
int xorif_set_fhi_src_mac_addr (int port, const uint8_t address[])
Set the source ethernet MAC address for the specified port.
Parameters
[in] port Ethernet port
[in] address MAC address (6 byte array)
Returns
XORIF_SUCCESS on success
Error code on failure
References WRITE_REG_OFFSET, xorif_fhi_get_num_eth_ports(), XORIF_INVALID_ETH_PORT, and XORIF_SUCCESS.
int xorif_set_fhi_vlan_tag (int port, uint16_t tag)
Set the VLAN tag for the specified port.
Parameters
[in] port Ethernet port
[in] tag VLAN tag (ID bits 0-11; DEI bit 12; PCP bits 13-15)
Returns
XORIF_SUCCESS on success
Error code on failure
References WRITE_REG_OFFSET, xorif_fhi_get_num_eth_ports(), XORIF_INVALID_ETH_PORT, and XORIF_SUCCESS.
int xorif_set_ru_ports (uint16_t ru_bits, uint16_t ss_bits, uint16_t mask, uint16_t user_val, uint16_t prach_val, uint16_t ssb_val)
Set the RU port ID bits (as either user/PRACH/SSB spatial streams).
Parameters
[in] ru_bits RU ID length (in bits)
[in] ss_bits Spatial stream length (in bits)
[in] mask Mask used when testing for user/PRACH/SSB value
[in] user_val User ID value (identifies regular U-plane spatial streams)
[in] prach_val PRACH ID value (identifies PRACH spatial streams)
[in] ssb_val SSB ID value (identifies SSB spatial streams)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
The RU bits defined by the call to xorif_set_fhi_eaxc_id. The present function defines additional masks/values which are used to split the RU ports into user/PRACH/SSB spatial streams. The ru_bits define the total size of the RU ID field; the ss_bits define the number of LSBs that are used the specify the spatial stream ID; the remaining MSBs (ru_bits - ss_bits) define a mask which identifies the spatial stream as user/PRACH/SSB/...
References binary_mask_string(), xorif_fhi_caps::ss_id_limit, WRITE_REG, XORIF_INVALID_EAXC_ID, and XORIF_SUCCESS.
int xorif_write_fhi_reg (const char * name, uint32_t value)
Utility function to write a field to the Front Haul Interface regsiter map.
Parameters
[in] name Register field name
[in] value The value to write to the register
Returns
XORIF_SUCCESS on success
Error code on failure
References reg_info::addr, find_register(), xorif_device_info::io, reg_info::mask, reg_info::shift, reg_info::width, write_reg(), XORIF_REGISTER_NOT_FOUND, and XORIF_SUCCESS.
int xorif_write_fhi_reg_offset (const char * name, uint16_t offset, uint32_t value)
Utility function to write a field to the Front Haul Interface regsiter map.
Parameters
[in] name Register field name
[in] offset Offset to be used with register (useful for repeated register banks)
[in] value The value to write to the register
Returns
XORIF_SUCCESS on success
Error code on failure
References reg_info::addr, find_register(), xorif_device_info::io, reg_info::mask, reg_info::shift, reg_info::width, write_reg(), XORIF_REGISTER_NOT_FOUND, and XORIF_SUCCESS.