ORAN-RADIO-IF: Libxorif-api
Libxorif-api
Data Structures
struct xorif_caps
struct xorif_fhi_caps
struct xorif_cc_config
struct xorif_cc_alloc
struct xorif_fhi_eth_stats
Functions
int xorif_get_state (void)
void xorif_debug (int level)
int xorif_init (const char *fh_dev_name, const char *bf_dev_name)
uint32_t xorif_get_sw_version (void)
struct xorif_caps * xorif_get_capabilities (void)
int xorif_has_front_haul_interface (void)
int xorif_has_beamformer (void)
int xorif_configure_cc (uint16_t cc)
int xorif_enable_cc (uint16_t cc)
int xorif_disable_cc (uint16_t cc)
int xorif_set_cc_config (uint16_t cc, const struct xorif_cc_config *ptr)
int xorif_get_cc_config (uint16_t cc, struct xorif_cc_config *ptr)
int xorif_set_cc_num_rbs (uint16_t cc, uint16_t num_rbs)
int xorif_set_cc_numerology (uint16_t cc, uint16_t numerology, uint16_t extended_cp)
int xorif_set_cc_numerology_ssb (uint16_t cc, uint16_t numerology, uint16_t extended_cp)
int xorif_set_cc_time_advance (uint16_t cc, uint32_t deskew, uint32_t advance_ul, uint32_t advance_dl)
int xorif_set_cc_dl_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
int xorif_set_cc_ul_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
int xorif_set_cc_iq_compression_ssb (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
int xorif_set_cc_bw_compression (uint16_t cc, uint16_t bit_width, enum xorif_bw_comp comp_method)
int xorif_set_cc_dl_sections_per_symbol (uint16_t cc, uint16_t num_sections)
int xorif_set_cc_ul_sections_per_symbol (uint16_t cc, uint16_t num_sections)
int xorif_set_cc_frames_per_symbol (uint16_t cc, uint16_t num_frames)
int xorif_set_cc_sections_per_symbol_ssb (uint16_t cc, uint16_t num_sections)
int xorif_set_cc_frames_per_symbol_ssb (uint16_t cc, uint16_t num_frames)
struct xorif_fhi_caps * xorif_get_fhi_capabilities (void)
void xorif_reset_fhi (uint16_t mode)
uint32_t xorif_get_fhi_hw_version (void)
uint32_t xorif_get_fhi_hw_revision (void)
uint32_t xorif_get_fhi_alarms (void)
int xorif_get_fhi_cc_alloc (uint16_t cc, struct xorif_cc_alloc *ptr)
int xorif_read_fhi_reg (const char *name, uint32_t *val)
int xorif_read_fhi_reg_offset (const char *name, uint16_t offset, uint32_t *val)
int xorif_write_fhi_reg (const char *name, uint32_t value)
int xorif_write_fhi_reg_offset (const char *name, uint16_t offset, uint32_t value)
int xorif_get_fhi_eth_stats (int port, struct xorif_fhi_eth_stats *ptr)
int xorif_set_fhi_dest_mac_addr (int port, const uint8_t address[])
int xorif_set_fhi_src_mac_addr (int port, const uint8_t address[])
int xorif_set_fhi_protocol (enum xorif_transport_protocol transport, uint16_t vlan, enum xorif_ip_mode ip_mode)
int xorif_set_fhi_vlan_tag (int port, uint16_t tag)
int xorif_set_fhi_packet_filter (int port, const uint32_t filter[16], uint16_t mask[4])
int xorif_enable_fhi_interrupts (uint32_t mask)
int xorif_set_fhi_eaxc_id (uint16_t du_bits, uint16_t bs_bits, uint16_t cc_bits, uint16_t ru_bits)
int xorif_set_ru_ports (uint16_t ru_bits, uint16_t ss_bits, uint16_t mask, uint16_t user_val, uint16_t prach_val, uint16_t ssb_val)
int xorif_register_fhi_isr (isr_func_t callback)
Detailed Description
Typedef Documentation
typedef void(* isr_func_t)(uint32_t status)
Type definition for alarm interrupt call-back function.
Enumeration Type Documentation
enum xorif_bw_comp
Enumerated type for beam-weight compression modes (ORAN values).
Enumerator
BW_COMP_NONE
No compression.
BW_COMP_BLOCK_FP
Block floating point compression.
BW_COMP_BLOCK_SCALE
Block scaling compression.
BW_COMP_U_LAW
U-Law compression.
BW_COMP_BEAMSPACE
Beamspace compression.
enum xorif_bw_comp_flags
Enumerated type for supported beam-weight compression modes (bit-map).
Enumerator
BW_COMP_NONE_SUPPORT
No compression.
BW_COMP_BLOCK_FP_SUPPORT
Block floating point compression.
BW_COMP_BLOCK_SCALE_SUPPORT
Block scaling compression.
BW_COMP_U_LAW_SUPPORT
U-Law compression.
BW_COMP_BEAMSPACE_SUPPORT
Beamspace compression.
enum xorif_error_codes
Enumerated type for error/status codes.
Enumerator
XORIF_OPERATIONAL_ERRORS
(Place holder for operational errors)
XORIF_NULL_POINTER
Attempt to access memory with null pointer.
XORIF_REGISTER_NOT_FOUND
Unknown register name.
XORIF_MEMORY_ALLOCATION_FAIL
Memory allocation fail.
XORIF_CONFIGURATION_ERRORS
(Place holder for configuration errors)
XORIF_INVALID_CC
Component carrier instance is not valid.
XORIF_INVALID_RBS
Number of RBs is not valid.
XORIF_INVALID_CONFIG
Invalid configuration (general error)
XORIF_NUMEROLOGY_NOT_SUPPORTED
Requested numerology is not supported.
XORIF_COMP_MODE_NOT_SUPPORTED
Requested compression mode is not supported.
XORIF_MAX_CTRL_SYM_EXCEEDED
Number of control symbols exceeds available space.
XORIF_MAX_DATA_SYM_EXCEEDED
Number of data symbols exceeds available space.
XORIF_BUFFER_SPACE_EXCEEDED
Required buffer space exceeds available space.
XORIF_INVALID_ETH_PORT
Invalid ethernet port number.
XORIF_INVALID_EAXC_ID
The specified eAxC ID is invalid.
XORIF_BEAMFORMER_ERRORS
(Place holder for beamformer-specific errors)
XORIF_SCHEDULE_TABLE_EXCEEDED
Out of space in beamformer schedule table.
XORIF_FRAME_WORK_ERRORS
(Place holder for library / libmetal errors)
XORIF_LIBMETAL_ERROR
Error with libmetal framework.
XORIF_OTHER_ERRORS
(Place holder for other errors)
XORIF_INVALID_RESULT
Represents an invalid result.
XORIF_SUCCESS
Success! No error!
XORIF_FAILURE
Failure return code.
enum xorif_fhi_alarms
Enumerations for Front-Haul Interface alarm/status information.
Enumerator
FRAMER_RESET_STATUS
"Framer" reset status
DEFRAMER_RESET_STATUS
"De-framer" reset status
DEFRAMER_FIFO_OF
"De-framer" FIFO over-flow
DEFRAMER_FIFO_UF
"De-framer" FIFO under-flow
DEFRAMER_CIRC_BUFF_OF
"De-framer" circular buffer over-flow
DEFRAMER_CIRC_BUFF_PTR_OF
"De-framer" circular buffer pointer over-flow
FRAMER_FIFO_OF
"Framer" FIFO over-flow
FRAMER_FIFO_UF
"Framer" FIFO under-flow
FRAMER_PRACH_SECTION_OF
PRACH section over-flow.
FRAMER_PRACH_SECTION_NF
PRACH section not-found.
AXI_TIMEOUT
AXI time-out.
enum xorif_ip_mode
Enumerations for supported Front-Haul IP modes.
Enumerator
IP_MODE_RAW
Raw.
IP_MODE_IPV4
IPv4.
IP_MODE_IPV6
IPv6.
enum xorif_iq_comp
Enumerated type for IQ compression modes (ORAN values).
Enumerator
IQ_COMP_NONE
No compression.
IQ_COMP_BLOCK_FP
Block floating point compression.
IQ_COMP_BLOCK_SCALE
Block scaling compression.
IQ_COMP_U_LAW
U-Law compression.
IQ_COMP_MODULATION
Modulation compression.
enum xorif_iq_comp_flags
Enumerated type for supported IQ compression modes (bit-map).
Enumerator
IQ_COMP_NONE_SUPPORT
No compression.
IQ_COMP_BLOCK_FP_SUPPORT
Block floating point compression.
IQ_COMP_BLOCK_SCALE_SUPPORT
Block scaling compression.
IQ_COMP_U_LAW_SUPPORT
U-Law compression.
IQ_COMP_MODULATION_SUPPORT
Modulation compression.
enum xorif_numerology_flags
Enumerated type for supported numerologies (bit-map)
Enumerator
NUMEROLOGY_0_SUPPORT
Numerology 0 (15kHz) supported.
NUMEROLOGY_1_SUPPORT
Numerology 1 (30kHz) supported.
NUMEROLOGY_2_SUPPORT
Numerology 2 (60kHz) supported.
NUMEROLOGY_3_SUPPORT
Numerology 3 (120kHz) supported.
NUMEROLOGY_4_SUPPORT
Numerology 4 (240kHz) supported.
enum xorif_transport_protocol
Enumerations for supported Front-Haul Interface transport protocols.
Enumerator
PROTOCOL_ECPRI
eCPRI
PROTOCOL_IEEE_1914_3
IEEE 1914.3.
Function Documentation
void xorif_clear_fhi_alarms (void)
Clear alarms for Front Haul Interface.
Referenced by xorif_reset_fhi().
void xorif_clear_fhi_stats (void)
Clear stats / counters for Front Haul Interface.
References WRITE_REG_RAW.
Referenced by xorif_reset_fhi().
int xorif_configure_cc (uint16_t cc)
Configure a component carrier.
Parameters
[in] cc Component carrier to configure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_caps::max_cc, xorif_cc_config::num_rbs, xorif_cc_config::numerology, xorif_cc_config::numerology_ssb, xorif_fhi_configure_cc(), xorif_has_beamformer(), XORIF_INVALID_CC, XORIF_INVALID_CONFIG, and XORIF_SUCCESS.
void xorif_debug (int level)
Set debug level for the library.
Parameters
[in] level Debug level (0 = no debug, 1 = minimal, 2 = verbose)
int xorif_disable_cc (uint16_t cc)
Disables the specified component carrier.
Parameters
[in] cc Component carrier to configure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_caps::max_cc, xorif_fhi_cc_disable(), and XORIF_INVALID_CC.
int xorif_enable_cc (uint16_t cc)
Enables the specified component carrier.
Parameters
[in] cc Component carrier to configure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_caps::max_cc, xorif_fhi_cc_enable(), and XORIF_INVALID_CC.
int xorif_enable_fhi_interrupts (uint32_t mask)
Enable / disable Front Haul Interface interrupts.
Parameters
[in] mask Mask (bit-map of interrupt sources)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
The mask bits are the same as in the enum xorif_fhi_alarms.
References WRITE_REG, WRITE_REG_RAW, and XORIF_SUCCESS.
void xorif_finish (void)
Finalize / close the API s/w.
References xorif_device_info::dev, and xorif_device_info::dev_name.
struct xorif_caps* xorif_get_capabilities (void)
Get ORAN Radio Interface capabilities.
Returns
Pointer to capabilities structure
int xorif_get_cc_config (uint16_t cc, struct xorif_cc_config * ptr)
Get the configuration for the component carrier.
Parameters
[in] cc Component carrier to configure
[in,out] ptr Pointer to component carrier configuration structure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_fhi_get_max_cc(), XORIF_INVALID_CC, XORIF_NULL_POINTER, and XORIF_SUCCESS.
uint32_t xorif_get_fhi_alarms (void)
Get alarms for Front Haul Interface.
Returns
Bit-map of alarm status (see enum xorif_fhi_alarms)
struct xorif_fhi_caps* xorif_get_fhi_capabilities (void)
Get capabilities from Front-Haul Interface.
Returns
Pointer to capabilities structure
int xorif_get_fhi_cc_alloc (uint16_t cc, struct xorif_cc_alloc * ptr)
Retrieve the configured allocation for the specified component carrier.
Parameters
[in] cc Component carrier
[in,out] ptr Pointer to component carrier allocation structure
Returns
XORIF_SUCCESS on success
Error code on failure
References MAX_NUM_CC, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, XORIF_NULL_POINTER, and XORIF_SUCCESS.
int xorif_get_fhi_eth_stats (int port, struct xorif_fhi_eth_stats * ptr)
Get Front Haul Interface Ethernet statistics for the specified port.
Parameters
[in] port Ethernet port
[in,out] ptr Pointer to component statistics data structure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_fhi_eth_stats::offset_earliest_c_pkt, xorif_fhi_eth_stats::offset_earliest_u_pkt, xorif_fhi_eth_stats::oran_rx_bit_rate, xorif_fhi_eth_stats::oran_rx_corrupt, xorif_fhi_eth_stats::oran_rx_early, xorif_fhi_eth_stats::oran_rx_early_c, xorif_fhi_eth_stats::oran_rx_error_drop, xorif_fhi_eth_stats::oran_rx_late, xorif_fhi_eth_stats::oran_rx_late_c, xorif_fhi_eth_stats::oran_rx_on_time, xorif_fhi_eth_stats::oran_rx_on_time_c, xorif_fhi_eth_stats::oran_rx_total, xorif_fhi_eth_stats::oran_rx_total_c, xorif_fhi_eth_stats::oran_tx_total, xorif_fhi_eth_stats::oran_tx_total_c, READ_REG_OFFSET, xorif_fhi_eth_stats::total_rx_bad_fcs_cnt, xorif_fhi_eth_stats::total_rx_bad_pkt_cnt, xorif_fhi_eth_stats::total_rx_bit_rate, xorif_fhi_eth_stats::total_rx_good_pkt_cnt, WRITE_REG, XORIF_FAILURE, xorif_fhi_get_num_eth_ports(), XORIF_INVALID_ETH_PORT, and XORIF_SUCCESS.
uint32_t xorif_get_fhi_hw_revision (void)
Returns the Front Haul Interface h/w internal revision number.
Returns
Revision
References READ_REG.
uint32_t xorif_get_fhi_hw_version (void)
Returns the Front Haul Interface h/w version.
Returns
Version (major = bits[24..31], minor = bits[16..23], version = bits[8..15])
References READ_REG.
int xorif_get_state (void)
Returns the current state of the library.
Returns
0 = not operational
1 = operational
uint32_t xorif_get_sw_version (void)
Return the s/w version.
Returns
Version (major = bits[24..31], minor = bits[16..23], version = bits[8..15])
int xorif_has_beamformer (void)
Check if there is a beamformer in the system.
Returns
0 = false (no)
1 = true (yes)
Referenced by xorif_configure_cc(), and xorif_set_cc_config().
int xorif_has_front_haul_interface (void)
Check if there is a front-haul interface in the system.
Returns
0 = false (no)
1 = true (yes)
References xorif_device_info::dev, and xorif_device_info::status.
int xorif_init (const char * fh_dev_name, const char * bf_dev_name)
Initialize the API s/w.
Parameters
[in] fh_dev_name Device name of the Front Haul Interface (leave as NULL for default)
[in] bf_dev_name Device name of the Beamformer (leave as NULL for default)
Returns
XORIF_SUCCESS on success
Error code on failure
References add_device(), get_device_name(), xorif_fhi_init_device(), XORIF_LIBMETAL_ERROR, and XORIF_SUCCESS.
int xorif_read_fhi_reg (const char * name, uint32_t * val)
Utility function to read a field from the Front Haul Interface register map.
Parameters
[in] name Register field name
[in,out] val Pointer to write back the read value
Returns
XORIF_SUCCESS on success
Error code on failure
References reg_info::addr, find_register(), xorif_device_info::io, reg_info::mask, read_reg(), reg_info::shift, reg_info::width, XORIF_REGISTER_NOT_FOUND, and XORIF_SUCCESS.
int xorif_read_fhi_reg_offset (const char * name, uint16_t offset, uint32_t * val)
Utility function to read a field from the Front Haul Interface register map.
Parameters
[in] name Register field name
[in] offset Offset to be used with register (useful for repeated register banks)
[in,out] val Pointer to write back the read value
Returns
XORIF_SUCCESS on success
Error code on failure
References reg_info::addr, find_register(), xorif_device_info::io, reg_info::mask, read_reg(), reg_info::shift, reg_info::width, XORIF_REGISTER_NOT_FOUND, and XORIF_SUCCESS.
int xorif_register_fhi_isr (isr_func_t callback)
Register a call-back function for Front Haul Interface alarm interrupts.
Parameters
[in] callback Function pointer for call-back
Returns
XORIF_SUCCESS on success
Error code on failure
References XORIF_SUCCESS.
Referenced by main().
void xorif_reset_fhi (uint16_t mode)
Reset the Front Haul Interface.
Parameters
[in] mode Reset mode (0 = immediate, 1 = hold in reset)
Note
When the mode = 1, the module is held in the reset state. Call the function again with mode = 0 to release the reset and to reset normally. This can be useful when coordinating the reset with other devices / modules. Use mode = 0 to perform the reset immediately.
References WRITE_REG, xorif_clear_fhi_alarms(), and xorif_clear_fhi_stats().
Referenced by xorif_fhi_init_device().
int xorif_set_cc_bw_compression (uint16_t cc, uint16_t bit_width, enum xorif_bw_comp comp_method)
Configure the beam-weight compression for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] bit_width Bit width (0-16)
[in] comp_method Compression method
Returns
XORIF_SUCCESS on success
Error code on failure
Note
For alignment with O-RAN standard, a bit_width value of 0 is equivalent to 16.
References xorif_cc_config::bw_comp_meth, xorif_cc_config::bw_comp_width, check_bw_comp_mode(), XORIF_COMP_MODE_NOT_SUPPORTED, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_config (uint16_t cc, const struct xorif_cc_config * ptr)
Set the configuration for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] ptr Pointer to configuration structure
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::bw_comp_meth, xorif_cc_config::bw_comp_width, check_bw_comp_mode(), check_iq_comp_mode(), check_numerology(), xorif_cc_config::extended_cp, xorif_cc_config::extended_cp_ssb, xorif_cc_config::iq_comp_meth_dl, xorif_cc_config::iq_comp_meth_ssb, xorif_cc_config::iq_comp_meth_ul, xorif_cc_config::iq_comp_width_dl, xorif_cc_config::iq_comp_width_ssb, xorif_cc_config::iq_comp_width_ul, xorif_caps::max_cc, MAX_NUM_RBS, MIN_NUM_RBS, xorif_cc_config::num_rbs, xorif_cc_config::num_rbs_ssb, xorif_cc_config::numerology, xorif_cc_config::numerology_ssb, SSB_NUM_RBS, XORIF_COMP_MODE_NOT_SUPPORTED, xorif_has_beamformer(), XORIF_INVALID_CC, XORIF_INVALID_CONFIG, XORIF_INVALID_RBS, XORIF_NULL_POINTER, XORIF_NUMEROLOGY_NOT_SUPPORTED, and XORIF_SUCCESS.
int xorif_set_cc_dl_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
Configure the downlink IQ compression for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] bit_width Bit width (0-16)
[in] comp_method Compression method
Returns
XORIF_SUCCESS on success
Error code on failure
Note
For alignment with O-RAN standard, a bit_width value of 0 is equivalent to 16.
References check_iq_comp_mode(), xorif_cc_config::iq_comp_meth_dl, xorif_cc_config::iq_comp_width_dl, XORIF_COMP_MODE_NOT_SUPPORTED, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_dl_sections_per_symbol (uint16_t cc, uint16_t num_sections)
Configure the number of sections allowed per downlink symbol.
Parameters
[in] cc Component carrier to configure
[in] num_sections Maximmum number of sections per symbol
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::num_ctrl_per_sym_dl, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_frames_per_symbol (uint16_t cc, uint16_t num_frames)
Configure the number of Ethernet frames allowed per (downlink) symbol.
Parameters
[in] cc Component carrier to configure
[in] num_frames Maximmum number of Ethernet frames per symbol
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::num_frames_per_sym, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_frames_per_symbol_ssb (uint16_t cc, uint16_t num_frames)
Configure the number of Ethernet frames allowed per SSB symbol.
Parameters
[in] cc Component carrier to configure
[in] num_frames Maximmum number of Ethernet frames per symbol
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::num_frames_per_sym_ssb, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_iq_compression_ssb (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
Configure the SSB compression for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] bit_width Bit width (0-16)
[in] comp_method Compression method
Returns
XORIF_SUCCESS on success
Error code on failure
Note
For alignment with O-RAN standard, a bit_width value of 0 is equivalent to 16.
References check_iq_comp_mode(), xorif_cc_config::iq_comp_meth_ssb, xorif_cc_config::iq_comp_width_ssb, XORIF_COMP_MODE_NOT_SUPPORTED, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_num_rbs (uint16_t cc, uint16_t num_rbs)
Set the number of RBs for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] num_rbs Number of RBs
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_caps::max_cc, MAX_NUM_RBS, xorif_cc_config::num_rbs, XORIF_INVALID_CC, XORIF_INVALID_RBS, and XORIF_SUCCESS.
int xorif_set_cc_numerology (uint16_t cc, uint16_t numerology, uint16_t extended_cp)
Set the numerology for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] numerology Numerology
[in] extended_cp Extended CP mode (0 = no, 1 = yes) (numerology 2 only)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
This function also sets the same numerology for the SSB. If SSB requires a different numerology, then this can be specified explicitly.
References check_numerology(), xorif_cc_config::extended_cp, xorif_caps::max_cc, xorif_cc_config::numerology, XORIF_INVALID_CC, XORIF_NUMEROLOGY_NOT_SUPPORTED, and XORIF_SUCCESS.
int xorif_set_cc_numerology_ssb (uint16_t cc, uint16_t numerology, uint16_t extended_cp)
Set the numerology for the component carrier's SSB.
Parameters
[in] cc Component carrier to configure
[in] numerology Numerology
[in] extended_cp Extended CP mode (0 = no, 1 = yes) (numerology 2 only)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
This function is used to specify a numerology when different to the UL/DL numerology.
References check_numerology(), xorif_cc_config::extended_cp, xorif_cc_config::extended_cp_ssb, xorif_caps::max_cc, xorif_cc_config::numerology, xorif_cc_config::numerology_ssb, XORIF_INVALID_CC, XORIF_NUMEROLOGY_NOT_SUPPORTED, and XORIF_SUCCESS.
int xorif_set_cc_sections_per_symbol_ssb (uint16_t cc, uint16_t num_sections)
Configure the number of sections allowed per SSB symbol.
Parameters
[in] cc Component carrier to configure
[in] num_sections Maximmum number of sections per symbol
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::num_ctrl_per_sym_ssb, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_time_advance (uint16_t cc, uint32_t deskew, uint32_t advance_ul, uint32_t advance_dl)
Set the maximum deskew and control advance timing for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] deskew Maximum deskew time (in microseconds)
[in] advance_ul Maximum control advance in uplink (in microseconds)
[in] advance_dl Maximum control advance in downlink (in microseconds)
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::advance_dl, xorif_cc_config::advance_ul, xorif_cc_config::deskew, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_ul_iq_compression (uint16_t cc, uint16_t bit_width, enum xorif_iq_comp comp_method)
Configure the uplink IQ compression for the component carrier.
Parameters
[in] cc Component carrier to configure
[in] bit_width Bit width (0-16)
[in] comp_method Compression method
Returns
XORIF_SUCCESS on success
Error code on failure
Note
For alignment with O-RAN standard, a bit_width value of 0 is equivalent to 16.
References check_iq_comp_mode(), xorif_cc_config::iq_comp_meth_ul, xorif_cc_config::iq_comp_width_ul, XORIF_COMP_MODE_NOT_SUPPORTED, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_cc_ul_sections_per_symbol (uint16_t cc, uint16_t num_sections)
Configure the number of sections allowed per uplink symbol.
Parameters
[in] cc Component carrier to configure
[in] num_sections Maximmum number of sections per symbol
Returns
XORIF_SUCCESS on success
Error code on failure
References xorif_cc_config::num_ctrl_per_sym_ul, xorif_fhi_get_max_cc(), XORIF_INVALID_CC, and XORIF_SUCCESS.
int xorif_set_fhi_dest_mac_addr (int port, const uint8_t address[])
Set the destination ethernet MAC address for the specified port.
Parameters
[in] port Ethernet port
[in] address MAC address (6 byte array)
Returns
XORIF_SUCCESS on success
Error code on failure
References WRITE_REG_OFFSET, xorif_fhi_get_num_eth_ports(), XORIF_INVALID_ETH_PORT, and XORIF_SUCCESS.
int xorif_set_fhi_eaxc_id (uint16_t du_bits, uint16_t bs_bits, uint16_t cc_bits, uint16_t ru_bits)
Set the eAxC ID (c.f.
ecpriRtcid and ecpriPcid)
Parameters
[in] du_bits DU ID length (in bits)
[in] bs_bits BS ID length (in bits)
[in] cc_bits CC ID length (in bits)
[in] ru_bits RU ID length (in bits)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
The eAxC ID is 16 bits, and the total length of the 4 fields should equal 16. See xorif_set_ru_ports for setting the spatial stream mask/values.
References binary_mask_string(), xorif_fhi_caps::bs_id_limit, xorif_fhi_caps::cc_id_limit, xorif_fhi_caps::du_id_limit, xorif_fhi_caps::ru_id_limit, WRITE_REG, XORIF_INVALID_EAXC_ID, and XORIF_SUCCESS.
int xorif_set_fhi_packet_filter (int port, const uint32_t filter[16], uint16_t mask[4])
Set the packet filter for the specified port.
Parameters
[in] port Ethernet port
[in] filter Pointer to an array of 16 x 32-bit words
[in] mask Pointer to an array of 4 x 16-bit words
Returns
XORIF_SUCCESS on success
Error code on failure
Note
The packet filter is defined by 4 filter words each 128-bits (16 bytes) wide. In the IP core's register map, each filter word is arranged as 4 x 32-bit words. Each filter word has an associated mask register which indicates whether a specific byte of the filter is used or not (if bit[X] = 0 then byte[X] of the filter word is used; if bit[x] = 1 then byte[x] of the filter word is not used). (See pg370-oran-radio-if document for full details).
References xorif_fhi_get_num_eth_ports(), XORIF_INVALID_ETH_PORT, and XORIF_SUCCESS.
Referenced by xorif_set_fhi_protocol().
int xorif_set_fhi_protocol (enum xorif_transport_protocol transport, uint16_t vlan, enum xorif_ip_mode ip_mode)
Set the protocol and IP mode.
Parameters
[in] transport Transport protocol (eCPRI, IEEE 1914.3)
[in] vlan VLAN tagging mode (0 = no VLAN, 1 = add VLAN tag)
[in] ip_mode IP mode (Raw, IPv4, IPv6)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
In addition to configuring the protocol, this function also configures the packet filters appropriately for all the Ethernet ports. If additional configuration of the packet filter is required, then this should be done after the call to this function.
References IP_MODE_RAW, PROTOCOL_ECPRI, PROTOCOL_IEEE_1914_3, WRITE_REG, xorif_fhi_get_num_eth_ports(), xorif_set_fhi_packet_filter(), and XORIF_SUCCESS.
int xorif_set_fhi_src_mac_addr (int port, const uint8_t address[])
Set the source ethernet MAC address for the specified port.
Parameters
[in] port Ethernet port
[in] address MAC address (6 byte array)
Returns
XORIF_SUCCESS on success
Error code on failure
References WRITE_REG_OFFSET, xorif_fhi_get_num_eth_ports(), XORIF_INVALID_ETH_PORT, and XORIF_SUCCESS.
int xorif_set_fhi_vlan_tag (int port, uint16_t tag)
Set the VLAN tag for the specified port.
Parameters
[in] port Ethernet port
[in] tag VLAN tag (ID bits 0-11; DEI bit 12; PCP bits 13-15)
Returns
XORIF_SUCCESS on success
Error code on failure
References WRITE_REG_OFFSET, xorif_fhi_get_num_eth_ports(), XORIF_INVALID_ETH_PORT, and XORIF_SUCCESS.
int xorif_set_ru_ports (uint16_t ru_bits, uint16_t ss_bits, uint16_t mask, uint16_t user_val, uint16_t prach_val, uint16_t ssb_val)
Set the RU port ID bits (as either user/PRACH/SSB spatial streams).
Parameters
[in] ru_bits RU ID length (in bits)
[in] ss_bits Spatial stream length (in bits)
[in] mask Mask used when testing for user/PRACH/SSB value
[in] user_val User ID value (identifies regular U-plane spatial streams)
[in] prach_val PRACH ID value (identifies PRACH spatial streams)
[in] ssb_val SSB ID value (identifies SSB spatial streams)
Returns
XORIF_SUCCESS on success
Error code on failure
Note
The RU bits defined by the call to xorif_set_fhi_eaxc_id. The present function defines additional masks/values which are used to split the RU ports into user/PRACH/SSB spatial streams. The ru_bits define the total size of the RU ID field; the ss_bits define the number of LSBs that are used the specify the spatial stream ID; the remaining MSBs (ru_bits - ss_bits) define a mask which identifies the spatial stream as user/PRACH/SSB/...
References binary_mask_string(), xorif_fhi_caps::ss_id_limit, WRITE_REG, XORIF_INVALID_EAXC_ID, and XORIF_SUCCESS.
int xorif_write_fhi_reg (const char * name, uint32_t value)
Utility function to write a field to the Front Haul Interface regsiter map.
Parameters
[in] name Register field name
[in] value The value to write to the register
Returns
XORIF_SUCCESS on success
Error code on failure
References reg_info::addr, find_register(), xorif_device_info::io, reg_info::mask, reg_info::shift, reg_info::width, write_reg(), XORIF_REGISTER_NOT_FOUND, and XORIF_SUCCESS.
int xorif_write_fhi_reg_offset (const char * name, uint16_t offset, uint32_t value)
Utility function to write a field to the Front Haul Interface regsiter map.
Parameters
[in] name Register field name
[in] offset Offset to be used with register (useful for repeated register banks)
[in] value The value to write to the register
Returns
XORIF_SUCCESS on success
Error code on failure
References reg_info::addr, find_register(), xorif_device_info::io, reg_info::mask, reg_info::shift, reg_info::width, write_reg(), XORIF_REGISTER_NOT_FOUND, and XORIF_SUCCESS.