ORAN-RADIO-IF: Protocol_ecpri
Protocol_ecpri
Data Structures
struct ecpri_header_s
struct ecpri_rma_msg_s
struct ecpri_owdm_msg_s
struct ecpri_rmr_msg_s
Functions
int ecpri_help_func (int argc, char **argv, char *resp)
int ecpri_owdm_req_func (int argc, char **argv, char *resp)
int ecpri_owdm_res_func (int argc, char **argv, char *resp)
int ecpri_owdm_limit_func (int argc, char **argv, char *resp)
int ecpri_rma_read_func (int argc, char **argv, char *resp)
int ecpri_rma_write_func (int argc, char **argv, char *resp)
int ecpri_test_mesg_func (int argc, char **argv, char *resp)
int ecpri_rmr_req_func (int argc, char **argv, char *resp)
int owdm_send_request (uint8_t type, char *dest_addr)
int rma_send_request (int type, char *dest_addr, char *addr, char *length, char *values)
int test_mesg_send_request (char *dest_addr, char *dest_port)
int rma_get_response (int type, char *addr, int *length, char **values)
int rmr_send_request (char *dest_addr)
int rmr_get_response (char *addr, char **values)
int ecpri_func (int argc, char **argv, char *resp)
int proto_ecpri_handle_incoming_rma (uint8_t *buffer, uint16_t data_len, int fd, struct sockaddr_in *src)
int proto_ecpri_handle_incoming_owdm (uint8_t *buffer, uint16_t data_len, int fd, struct sockaddr_in *src, struct timespec *ts)
int proto_ecpri_handle_incoming_rmr (uint8_t *buffer, uint16_t data_len, int fd, struct sockaddr_in *src)
int proto_ecpri_handle_incoming_event (uint8_t *buffer, uint16_t data_len, int fd, struct sockaddr_in *src)
int proto_ecpri_handle_incoming_test_mesg (uint8_t *buffer, uint16_t data_len, int fd, struct sockaddr_in *src)
int proto_ecpri_send (uint8_t *data, uint16_t length, ecpri_message_type_t type, int sock_d, struct sockaddr_in *dest)
int proto_ecpri_recv (uint8_t **data, uint16_t *length, ecpri_message_type_t *type, int sock_d, struct sockaddr_in *src, uint8_t *ts)
int proto_ecpri_handle_timestamps (int sock_d, int errQueue, uint8_t *ts)
int proto_ecpri_rma_send_request (int type, uint16_t data_len, struct sockaddr_in *dest, uint64_t offset, uint8_t *values)
int proto_ecpri_rma_get_response (int type, int *length, struct sockaddr_in *src, uint8_t **values)
int proto_ecpri_owdm_send_req_get_ts (uint8_t *msg, uint16_t len, struct sockaddr_in *dest, int send_ts)
int proto_ecpri_owdm_send_request (uint8_t type, struct sockaddr_in *dest)
int ecpri_owdm_calc_delay (owdm_ts_msg_type *t1, owdm_ts_msg_type *t2, owdm_result_type *owdm_result)
int proto_ecpri_rmr_send_request (struct sockaddr_in *dest)
int proto_ecpri_rmr_get_response (struct sockaddr_in *src)
int proto_ecpri_handle_incoming_msg (int fd, short revents, char *command)
void proto_ecpri_get_owdm_result (int *req_no, int *resp_no, ecpri_owdm_direction_type *direction, struct in_addr *node, unsigned long long *secs, unsigned long *nsecs)
int proto_ecpri_test_mesg_send (struct sockaddr_in *dest)
void proto_ecpri_set_owdm_limit (long limit)
Detailed Description
Sample eCPRI protocol library.
Macro Definition Documentation
#define ECPRI_HELP_STR "generates this list of commands\n"
ECPRI_HELP_STR Help text for the ecpri module "help" option.
#define ECPRI_MAX_COMMANDS 9
ECPRI_MAX_COMMANDS Number of commands handled by the ecpri module.
#define ECPRI_OWDM_LIMIT_STR "ecpri owdm_limit - Sets the report threshold of the OWDM measurement (nsecs), or disables reporting if 0\n"
ECPRI_OWDM_LIMIT_STR Help text for the ecpri module "owdm_limit" option.
Referenced by ecpri_owdm_limit_func().
#define ECPRI_OWDM_MSG_ACTION_FOL_UP (0x5)
ECPRI_OWDM_MSG_ACTION_FOL_UP eCPRI OWDM follow-up flag.
Referenced by proto_ecpri_handle_incoming_owdm(), and proto_ecpri_owdm_send_req_get_ts().
#define ECPRI_OWDM_MSG_ACTION_REM_REQ (0x3)
ECPRI_OWDM_MSG_ACTION_REM_REQ eCPRI OWDM remote action request flag.
Referenced by proto_ecpri_owdm_send_request().
#define ECPRI_OWDM_MSG_ACTION_REM_REQ_FOL_UP (0x4)
ECPRI_OWDM_MSG_ACTION_REM_REQ_FOL_UP OWDM rem act req with follow-up flag.
Referenced by ecpri_owdm_req_func(), proto_ecpri_handle_incoming_owdm(), and proto_ecpri_owdm_send_request().
#define ECPRI_OWDM_MSG_ACTION_REQ (0)
ECPRI_OWDM_MSG_ACTION_REQ eCPRI OWDM action request flag.
Referenced by proto_ecpri_owdm_send_request().
#define ECPRI_OWDM_MSG_ACTION_REQ_FOL_UP (0x1)
ECPRI_OWDM_MSG_ACTION_REQ_FOL_UP eCPRI OWDM action req with follow-up flag.
Referenced by ecpri_owdm_req_func(), proto_ecpri_handle_incoming_owdm(), and proto_ecpri_owdm_send_request().
#define ECPRI_OWDM_MSG_ACTION_RESP (0x2)
ECPRI_OWDM_MSG_ACTION_RESP eCPRI OWDM action response flag.
Referenced by proto_ecpri_handle_incoming_owdm().
#define ECPRI_OWDM_REQ_STR "ecpri owdm_req <addr> <type> - Request an OWDM measurement to <addr> of type <to_remote|from_remote>\n"
ECPRI_OWDM_REQ_STR Help text for the ecpri module "owdm_req" option.
Referenced by ecpri_owdm_req_func().
#define ECPRI_OWDM_RES_STR "ecpri owdm_res - Returns the result of the last OWDM measurement, or \"Pending\" if still underway\n"
ECPRI_OWDM_RES_STR Help text for the ecpri module "owdm_res" option.
Referenced by ecpri_owdm_res_func().
#define ECPRI_PROTO_HEADER_SIZE (4)
ECPRI_PROTO_HEADER_SIZE Size of the eCPRI message header.
Referenced by proto_ecpri_recv(), and proto_ecpri_send().
#define ECPRI_PROTO_MAGIC_BYTE (0x10)
ECPRI_PROTO_MAGIC_BYTE Magic eCPRI message byte.
Referenced by proto_ecpri_recv(), and proto_ecpri_send().
#define ECPRI_RMA_MSG_FAIL (0x2)
ECPRI_RMA_MSG_FAIL eCPRI RMA request fail flag.
#define ECPRI_RMA_MSG_READ (0)
ECPRI_RMA_MSG_READ eCPRI RMA read flag.
Referenced by proto_ecpri_handle_incoming_rma(), proto_ecpri_rma_get_response(), rma_get_response(), and rma_send_request().
#define ECPRI_RMA_MSG_REQ (0)
ECPRI_RMA_MSG_REQ eCPRI RMA request flag.
Referenced by proto_ecpri_rma_send_request().
#define ECPRI_RMA_MSG_RESP (0x1)
ECPRI_RMA_MSG_RESP eCPRI RMA response flag.
Referenced by proto_ecpri_handle_incoming_rma(), and proto_ecpri_rma_get_response().
#define ECPRI_RMA_MSG_WR_NO_RESP (0x20)
ECPRI_RMA_MSG_WR_NO_RESP eCPRI RMA write with no response flag.
Referenced by proto_ecpri_handle_incoming_rma().
#define ECPRI_RMA_MSG_WRITE (0x10)
ECPRI_RMA_MSG_WRITE eCPRI RMA write flag.
Referenced by proto_ecpri_handle_incoming_rma(), proto_ecpri_rma_send_request(), rma_get_response(), and rma_send_request().
#define ECPRI_RMA_READ_STR "ecpri rma_read <ip_addr> <mem_addr> <length> - Request a read of <length> bytes at <mem_addr> from <ip_addr>\n"
ECPRI_RMA_READ_STR Help text for the ecpri module "rma_read" option.
Referenced by ecpri_rma_read_func().
#define ECPRI_RMA_WRITE_STR "ecpri rma_write <ip_addr> <mem_addr> <length> \"<bytes 1..length>\" - Request a write of <length> <bytes> to <mem_addr> at <ip_addr>\n"
ECPRI_RMA_WRITE_STR Help text for the ecpri module "rma_write" option.
Referenced by ecpri_rma_write_func().
#define ECPRI_RMR_MSG_CODE_OP_REM_RESET_REQ (0x1)
ECPRI_RMR_MSG_CODE_OP_REM_RESET_REQ eCPRI RMR request flag.
Referenced by proto_ecpri_handle_incoming_rmr(), and proto_ecpri_rmr_send_request().
#define ECPRI_RMR_MSG_CODE_OP_REM_RESET_RESP (0x2)
ECPRI_RMR_MSG_CODE_OP_REM_RESET_RESP eCPRI RMR response flag.
Referenced by proto_ecpri_handle_incoming_rmr(), and proto_ecpri_rmr_get_response().
#define ECPRI_RMR_REQ_STR "ecpri rmr_req <ip_addr> - Request a remote reset of <ip_addr>\n"
ECPRI_RMR_REQ_STR Help text for the ecpri module "rmr_req" option.
Referenced by ecpri_rmr_req_func().
#define ECPRI_TEST_MESG_STR "ecpri test_mesg <ip_addr> <dest_port> - TESTING - Send a test message to <dest_port>\n"
ECPRI_TEST_MESG_STR Help text for the ecpri module "test_mesg" option.
Referenced by ecpri_test_mesg_func().
#define ECPRI_USAGE_STR "Usage \"ecpri [args]\", try \"ecpri help\" for command list\n"
ECPRI_USAGE_STR Help text for the ecpri module.
Referenced by ecpri_func().
#define RMA_READ 1
RMA_READ Flag to indicate an RMA read operation.
Referenced by ecpri_rma_read_func(), rma_get_response(), and rma_send_request().
#define RMA_WRITE 2
RMA_WRITE Flag to indicate an RMA write operation.
Referenced by ecpri_rma_write_func().
Typedef Documentation
typedef struct ecpri_header_s ecpri_header_t
ecpri_header_t The eCPRI user-plane message header.
typedef enum ecpri_message_type_e ecpri_message_type_t
ecpri_message_type_t The types of eCPRI user-plane message.
typedef enum ecpri_owdn_direction ecpri_owdm_direction_type
ecpri_owdm_msg_t eCPRI OWDM direction.
typedef struct ecpri_owdm_msg_s ecpri_owdm_msg_t
ecpri_owdm_msg_t eCPRI OWDM message structure.
typedef struct ecpri_rma_msg_s ecpri_rma_msg_t
ecpri_rma_msg_t eCPRI RMA message structure.
typedef struct ecpri_rmr_msg_s ecpri_rmr_msg_t
ecpri_rmr_msg_t eCPRI RMR message structure.
typedef struct owdm_result owdm_result_type
Structure for holding an OWDM result message.
typedef struct owdm_ts_msg owdm_ts_msg_type
owdm_ts_msg_type Structure for holding an OWDM timestamp.
Enumeration Type Documentation
enum ecpri_message_type_e
ecpri_message_type_t The types of eCPRI user-plane message.
Enumerator
ECPRI_MSG_IQ_DATA
IQ Data.
ECPRI_MSG_BIT_SEQ
Bit Sequence.
ECPRI_MSG_RTC_DATA
Real-Time Control Data.
ECPRI_MSG_GENERIC_DATA
Generic Data.
ECPRI_MSG_RMA
Remote Memory Access.
ECPRI_MSG_OWDM
One-Way Delay Measurement.
ECPRI_MSG_REM_RESET
Remote Reset.
ECPRI_MSG_EVENT
Event Indication.
enum ecpri_owdn_direction
ecpri_owdm_msg_t eCPRI OWDM direction.
Enumerator
TO_REMOTE
Measure to remote from originator.
FROM_REMOTE
Measure to originator from remote.
Function Documentation
int ecpri_func (int argc, char ** argv, char * resp)
Parses the input command string and calls a handler function (if found).
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
1 if no commands tokens found.
2 if no handler found for command.
0 otherwise.
References ecpri_cmds, and ECPRI_USAGE_STR.
int ecpri_help_func (int argc, char ** argv, char * resp)
Returns help strings for eCPRI commands.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ecpri_cmds.
int ecpri_owdm_calc_delay (owdm_ts_msg_type * t1, owdm_ts_msg_type * t2, owdm_result_type * owdm_result)
Calculates the difference between two time-stamps as an OWDM result.
Parameters
[in] t1 Start time-stamp.
[in] t2 End time-stamp.
[in] owdm_result Difference between t1 and t2.
Returns
1.
References ecpri_report_limit.
Referenced by proto_ecpri_handle_incoming_owdm().
int ecpri_owdm_limit_func (int argc, char ** argv, char * resp)
Sets the reporting limit of the latest One-Way Delay Measurement.
This function calls the eCPRI protocol module to set the limit. If the specified threshold value is 0, reporting is disabled, otherwise all OWDM measurements over the limit (in nsecs) trigger an ILA write.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_OWDM_LIMIT_STR, and proto_ecpri_set_owdm_limit().
int ecpri_owdm_req_func (int argc, char ** argv, char * resp)
Requests a One-Way Delay Measurement to/from a remote node.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_OWDM_MSG_ACTION_REM_REQ_FOL_UP, ECPRI_OWDM_MSG_ACTION_REQ_FOL_UP, ECPRI_OWDM_REQ_STR, and owdm_send_request().
int ecpri_owdm_res_func (int argc, char ** argv, char * resp)
Gets the result of the latest One-Way Delay Measurement.
This function calls the eCPRI protocol module to retrieve the result.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_OWDM_RES_STR, proto_ecpri_get_owdm_result(), and TO_REMOTE.
int ecpri_rma_read_func (int argc, char ** argv, char * resp)
Requests a Remote Memory read from a remote node.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_RMA_READ_STR, rma_get_response(), RMA_READ, and rma_send_request().
int ecpri_rma_write_func (int argc, char ** argv, char * resp)
Requests a Remote Memory write to a remote node.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_RMA_WRITE_STR, rma_get_response(), rma_send_request(), and RMA_WRITE.
int ecpri_rmr_req_func (int argc, char ** argv, char * resp)
Requests a Remote Reset of a remote node.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_RMR_REQ_STR, rmr_get_response(), and rmr_send_request().
int ecpri_test_mesg_func (int argc, char ** argv, char * resp)
Sends a test message (generic data) to a remote node.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_TEST_MESG_STR, and test_mesg_send_request().
int owdm_send_request (uint8_t type, char * dest_addr)
Sends a One-Way Delay Measurement request to a remote node.
This function calls the eCPRI protocol module to format and send the message.
Parameters
[in] type The direction, either TO_REMOTE or FROM_REMOTE.
[in] dest_addr IP address of remote node.
Returns
0 if address is not valid.
Return value of proto_ecpri_owdm_send_request().
References proto_ecpri_owdm_send_request().
Referenced by ecpri_owdm_req_func().
void proto_ecpri_get_owdm_result (int * req_no, int * resp_no, ecpri_owdm_direction_type * direction, struct in_addr * node, unsigned long long * secs, unsigned long * nsecs)
Return the current OWDM result values.
Parameters
[out] req_no Latest OWDM request number.
[out] resp_no Latest OWDM response number.
[out] direction Direction of latest response.
[out] node Remote node of latest measurement.
[out] secs Seconds portion of latest delay value.
[out] nsecs Nano-seconds portion of latest delay value.
References owdm_req, and owdm_result.
Referenced by ecpri_owdm_res_func().
int proto_ecpri_handle_incoming_event (uint8_t * buffer, uint16_t data_len, int fd, struct sockaddr_in * src)
Handle an incoming eCPRI event message.
Dummy function that does nothing.
Parameters
[in] buffer Ignored.
[in] data_len Ignored.
[in] fd Ignored.
[in] src Ignored.
Returns
0.
Referenced by proto_ecpri_handle_incoming_msg().
int proto_ecpri_handle_incoming_msg (int fd, short revents, char * command)
Handle an eCPRI message received on the UDP/IP socket.
Parameters
[in] fd File handle of receiving socket.
[in] revents receive events on socket.
[in] command Ignored.
Returns
return value of proto_ecpri_handle_timestamps() if revent is POLLERR.
return value of proto_ecpri_recv() on POLLIN error.
return value of appropriate handler function if recognised.
0 on unhandled message type or revent not POLLIN or POLLERR.
References ECPRI_MSG_BIT_SEQ, ECPRI_MSG_EVENT, ECPRI_MSG_GENERIC_DATA, ECPRI_MSG_IQ_DATA, ECPRI_MSG_OWDM, ECPRI_MSG_REM_RESET, ECPRI_MSG_RMA, ECPRI_MSG_RTC_DATA, proto_ecpri_handle_incoming_event(), proto_ecpri_handle_incoming_owdm(), proto_ecpri_handle_incoming_rma(), proto_ecpri_handle_incoming_rmr(), proto_ecpri_handle_incoming_test_mesg(), proto_ecpri_handle_timestamps(), and proto_ecpri_recv().
Referenced by do_socket().
int proto_ecpri_handle_incoming_owdm (uint8_t * buffer, uint16_t data_len, int fd, struct sockaddr_in * src, struct timespec * ts)
Handle an incoming eCPRI Remote Memory Access message.
Parameters
[in] buffer Buffer containing incoming message.
[in] data_len Length of incoming message.
[in] fd Ignored.
[in] src IP address of remote node for replies and result.
[in] ts Time-stamp of received message.
Returns
-1 on short message received.
0 otherwise.
References ecpri_owdm_msg_s::action_type, ecpri_owdm_msg_s::comp, ecpri_owdm_calc_delay(), ECPRI_OWDM_MSG_ACTION_FOL_UP, ECPRI_OWDM_MSG_ACTION_REM_REQ_FOL_UP, ECPRI_OWDM_MSG_ACTION_REQ_FOL_UP, ECPRI_OWDM_MSG_ACTION_RESP, FROM_REMOTE, ecpri_owdm_msg_s::id, owdm_comp, owdm_msg, owdm_req, owdm_result, proto_ecpri_owdm_send_req_get_ts(), TO_REMOTE, ecpri_owdm_msg_s::ts_nsec, and ecpri_owdm_msg_s::ts_sec.
Referenced by proto_ecpri_handle_incoming_msg().
int proto_ecpri_handle_incoming_rma (uint8_t * buffer, uint16_t data_len, int fd, struct sockaddr_in * src)
Handle an incoming eCPRI Remote Memory Access message.
Parameters
[in] buffer Buffer containing incoming message.
[in] data_len Ignored.
[in] fd File handle of receiving/response socket.
[in] src IP address of remote node for replies.
Returns
return value of IP_API_Write() on write.
-1 on malloc failure.
0 on unhandled message type or read success.
References ecpri_rma_msg_s::address, ECPRI_MSG_RMA, ECPRI_RMA_MSG_READ, ECPRI_RMA_MSG_RESP, ECPRI_RMA_MSG_WR_NO_RESP, ECPRI_RMA_MSG_WRITE, ecpri_rma_msg_s::element_id, ecpri_rma_msg_s::id, ecpri_rma_msg_s::length, proto_ecpri_send(), and ecpri_rma_msg_s::rd_wr_req_resp.
Referenced by proto_ecpri_handle_incoming_msg().
int proto_ecpri_handle_incoming_rmr (uint8_t * buffer, uint16_t data_len, int fd, struct sockaddr_in * src)
Handle an incoming eCPRI Remote Reset message.
Simply sends a response message to acknowledge the RMR. Does not do a reset.
Parameters
[in] buffer Buffer containing incoming message.
[in] data_len Ignored.
[in] fd File handle of socket for response.
[in] src IP address of remote node for replies.
Returns
-1 on malloc failure.
0 otherwise.
References ecpri_rmr_msg_s::code_op, ECPRI_MSG_REM_RESET, ECPRI_RMR_MSG_CODE_OP_REM_RESET_REQ, ECPRI_RMR_MSG_CODE_OP_REM_RESET_RESP, ecpri_rmr_msg_s::id, and proto_ecpri_send().
Referenced by proto_ecpri_handle_incoming_msg().
int proto_ecpri_handle_incoming_test_mesg (uint8_t * buffer, uint16_t data_len, int fd, struct sockaddr_in * src)
Handle an incoming eCPRI test message (generic data).
Parameters
[in] buffer Buffer containing incoming message.
[in] data_len Ignored.
[in] fd Ignored.
[in] src Ignored.
Returns
0.
Referenced by proto_ecpri_handle_incoming_msg().
int proto_ecpri_handle_timestamps (int sock_d, int errQueue, uint8_t * ts)
Receives a message on the eCPRI protocol port.
This retrieves a message from the given remote IP address, checks if it is a valid eCPRI message, then returns the payload and the packet rx time-stamp (if present).
Parameters
[in] sock_d File handle of the receiving eCPRI socket.
[in] errQueue IP address of remote node.
[out] ts Pointer to packet rx time-stamp.
Returns
0 if short message received.
-1 if short socket control message received or malloc fails.
1 if time-stamp received.
length of payload otherwise.
Referenced by proto_ecpri_handle_incoming_msg(), and proto_ecpri_owdm_send_req_get_ts().
int proto_ecpri_owdm_send_req_get_ts (uint8_t * msg, uint16_t len, struct sockaddr_in * dest, int send_ts)
Send an OWDM request and optionally the tx time-stamp.
Sends a One-Way Delay Measurement request to a remote node, reads and saves the tx time-stamp for internal use, and if send_ts is non-zero sends a OWDM follow-up message to the remote node with the time-stamp.
Parameters
[in] msg Pointer to OWDM request message.
[in] len Length of message.
[in] dest IP address of remote node to send to.
[in] send_ts Pointer to buffer to put read data in.
Returns
Return value of proto_ecpri_send() for message if <= 0.
Return value of proto_ecpri_handle_timestamps() if < 0 or !send_ts.
Return value of proto_ecpri_send() for followup otherwise.
References ecpri_owdm_msg_s::action_type, ecpri_owdm_msg_s::comp, ECPRI_MSG_OWDM, ECPRI_OWDM_MSG_ACTION_FOL_UP, owdm_comp, owdm_msg, proto_ecpri_handle_timestamps(), proto_ecpri_send(), ecpri_owdm_msg_s::ts_nsec, and ecpri_owdm_msg_s::ts_sec.
Referenced by proto_ecpri_handle_incoming_owdm(), and proto_ecpri_owdm_send_request().
int proto_ecpri_owdm_send_request (uint8_t type, struct sockaddr_in * dest)
Send an OWDM request.
Parameters
[in] type Type of OWDM request message.
[in] dest IP address of remote node to send to.
See Also
ecpri_proto.h
Returns
-1 if type not supported or recognised.
Return value of proto_ecpri_owdm_send_req_get_ts() otherwise.
References ecpri_owdm_msg_s::action_type, ECPRI_OWDM_MSG_ACTION_REM_REQ, ECPRI_OWDM_MSG_ACTION_REM_REQ_FOL_UP, ECPRI_OWDM_MSG_ACTION_REQ, ECPRI_OWDM_MSG_ACTION_REQ_FOL_UP, ecpri_owdm_msg_s::id, owdm_req, and proto_ecpri_owdm_send_req_get_ts().
Referenced by owdm_send_request().
int proto_ecpri_recv (uint8_t ** data, uint16_t * length, ecpri_message_type_t * type, int sock_d, struct sockaddr_in * src, uint8_t * ts)
Receives a message on the eCPRI protocol port.
This retrieves a message from the given remote IP address, checks if it is a valid eCPRI message, then returns the payload and the packet rx time-stamp (if present).
Parameters
[out] data Pointer to memory buffer allocated by this function containing the payload data.
[out] length Length of payload received.
[out] type Received eCPRI message type.
[in] sock_d File handle of the receiving eCPRI socket.
[in] src IP address of remote node.
[out] ts Pointer to packet rx time-stamp.
Returns
0 if short message received.
-1 if short socket control message received or malloc fails.
1 if time-stamp received.
length of payload otherwise.
References ECPRI_PROTO_HEADER_SIZE, ECPRI_PROTO_MAGIC_BYTE, ecpri_header_s::length, ecpri_header_s::magic, and ecpri_header_s::type.
Referenced by proto_ecpri_handle_incoming_msg(), proto_ecpri_rma_get_response(), and proto_ecpri_rmr_get_response().
int proto_ecpri_rma_get_response (int type, int * length, struct sockaddr_in * src, uint8_t ** values)
Receives an RMA response from a remote node.
Parameters
[in] type Type of RMA message expected (Read or Write).
[out] length Length in bytes read/written.
[in] src IP address of remote node to receive from.
[out] values Pointer to buffer to put read data in.
Returns
-1 if malloc fails.
0 on success.
Return value of proto_ecpri_recv() if not an RMA message.
References ECPRI_MSG_RMA, ECPRI_RMA_MSG_READ, ECPRI_RMA_MSG_RESP, ecpri_rma_msg_s::length, proto_ecpri_recv(), and ecpri_rma_msg_s::rd_wr_req_resp.
Referenced by rma_get_response().
int proto_ecpri_rma_send_request (int type, uint16_t data_len, struct sockaddr_in * dest, uint64_t offset, uint8_t * values)
Sends an RMA request to a remote node.
Parameters
[in] type Type of RMA message (Read or Write).
[in] data_len Length in bytes to read/write.
[in] dest IP address of remote node.
[in] offset Remote memory address to read/write.
[in,out] values Pointer to buffer for read/write.
Returns
-1 if malloc fails.
Return value of proto_ecpri_send().
References ecpri_rma_msg_s::address, ECPRI_MSG_RMA, ECPRI_RMA_MSG_REQ, ECPRI_RMA_MSG_WRITE, ecpri_rma_msg_s::element_id, ecpri_rma_msg_s::id, ecpri_rma_msg_s::length, proto_ecpri_send(), and ecpri_rma_msg_s::rd_wr_req_resp.
Referenced by rma_send_request().
int proto_ecpri_rmr_get_response (struct sockaddr_in * src)
Get a Remote Reset response from a remote node.
Parameters
[in] src IP address of the remote node.
Returns
0 on valid response.
-1 other Remote Reset message.
return value of proto_ecpri_recv() otherwise.
References ecpri_rmr_msg_s::code_op, ECPRI_MSG_REM_RESET, ECPRI_RMR_MSG_CODE_OP_REM_RESET_RESP, and proto_ecpri_recv().
Referenced by rmr_get_response().
int proto_ecpri_rmr_send_request (struct sockaddr_in * dest)
Send a Remote Reset request to a remote node.
Parameters
[in] dest IP address of the remote node.
Returns
-1 if malloc fails.
return value of proto_ecpri_send() otherwise.
References ecpri_rmr_msg_s::code_op, ECPRI_MSG_REM_RESET, ECPRI_RMR_MSG_CODE_OP_REM_RESET_REQ, ecpri_rmr_msg_s::id, and proto_ecpri_send().
Referenced by rmr_send_request().
int proto_ecpri_send (uint8_t * data, uint16_t length, ecpri_message_type_t type, int sock_d, struct sockaddr_in * dest)
Sends an eCPRI protocol message to a remote node.
This takes the payload and adds the eCPRI message header before transmission.
Parameters
[in] data Pointer to the message payload.
[in] length Length of the payload.
[in] type eCPRI message type.
[in] sock_d File handle of the outbound socket.
[in] dest IP address of remote node.
Returns
0 if malloc fails.
Return value of sendto().
References ECPRI_PROTO_HEADER_SIZE, ECPRI_PROTO_MAGIC_BYTE, ecpri_header_s::length, ecpri_header_s::magic, and ecpri_header_s::type.
Referenced by proto_ecpri_handle_incoming_rma(), proto_ecpri_handle_incoming_rmr(), proto_ecpri_owdm_send_req_get_ts(), proto_ecpri_rma_send_request(), proto_ecpri_rmr_send_request(), and proto_ecpri_test_mesg_send().
void proto_ecpri_set_owdm_limit (long limit)
Set the reporting threshold for eCPRI OWDM measurements.
Parameters
[in] limit The limit value above which to issue a report.
References ecpri_report_limit.
Referenced by ecpri_owdm_limit_func().
int proto_ecpri_test_mesg_send (struct sockaddr_in * dest)
Send an eCPRI test message (generic data).
Sends a generic data message containing an incrementing sequence number.
Parameters
[in] dest IP address of the remote host to send to.
Returns
-1 on malloc failure.
return value of proto_ecpri_send() otherwise.
References ECPRI_MSG_GENERIC_DATA, proto_ecpri_send(), and SEQ_NUM.
Referenced by test_mesg_send_request().
int rma_get_response (int type, char * addr, int * length, char ** values)
Reads a Remote Memory Access response from a remote node.
This function calls the eCPRI protocol module to receive the message.
Parameters
[in] type Can be read or write.
[in] addr Ignored.
[in] length The number of bytes read/written.
[in] values Array of byte values read, or NULL on write.
Returns
Return value of proto_ecpri_rma_get_response().
References ECPRI_RMA_MSG_READ, ECPRI_RMA_MSG_WRITE, proto_ecpri_rma_get_response(), and RMA_READ.
Referenced by ecpri_rma_read_func(), and ecpri_rma_write_func().
int rma_send_request (int type, char * dest_addr, char * addr, char * length, char * values)
Sends a Remote Memory Access request to a remote node.
This function calls the eCPRI protocol module to format and send the message.
Parameters
[in] type Can be read or write.
[in] dest_addr IP address of remote node.
[in] addr The remote memory address to access.
[in] length The number of bytes to access.
[in] values Array of byte values to write, or NULL on read.
Returns
-1 if malloc failed.
0 if address is not valid.
Return value of proto_ecpri_rma_send_request().
References ECPRI_RMA_MSG_READ, ECPRI_RMA_MSG_WRITE, proto_ecpri_rma_send_request(), and RMA_READ.
Referenced by ecpri_rma_read_func(), and ecpri_rma_write_func().
int rmr_get_response (char * addr, char ** values)
Gets a Remote Reset response from a remote node.
This function calls the eCPRI protocol module to receive the message.
Parameters
[in] addr Address of the remote node to reset.
[out] values Pointer to string to place the response into.
Returns
Return value of proto_ecpri_rmr_get_response().
References proto_ecpri_rmr_get_response().
Referenced by ecpri_rmr_req_func().
int rmr_send_request (char * dest_addr)
Sends a Remote Reset request to a remote node.
This function calls the eCPRI protocol module to format and send the message.
Parameters
[in] dest_addr Address of the remote node to reset.
Returns
0 if address is not valid.
Return value of proto_ecpri_rmr_send_request().
References proto_ecpri_rmr_send_request().
Referenced by ecpri_rmr_req_func().
int test_mesg_send_request (char * dest_addr, char * dest_port)
Sends a test message (generic data) to a remote node.
This function calls the eCPRI protocol module to format and send the message.
Parameters
[in] dest_addr IP address of remote node.
[in] dest_port IP port address of the remote node.
Returns
0 if address is not valid.
Return value of proto_ecpri_test_mesg_send().
References proto_ecpri_test_mesg_send().
Referenced by ecpri_test_mesg_func().
Variable Documentation
commands_t ecpri_cmds[ECPRI_MAX_COMMANDS]
Initial value:
= {
    {"help", ECPRI_HELP_STR, ecpri_help_func},
    {"rma_read", ECPRI_RMA_READ_STR, ecpri_rma_read_func},
    {"rma_write", ECPRI_RMA_WRITE_STR, ecpri_rma_write_func},
    {"owdm_req", ECPRI_OWDM_REQ_STR, ecpri_owdm_req_func},
    {"owdm_res", ECPRI_OWDM_RES_STR, ecpri_owdm_res_func},
    {"owdm_limit", ECPRI_OWDM_LIMIT_STR, ecpri_owdm_limit_func},
    {"test_mesg", ECPRI_TEST_MESG_STR, ecpri_test_mesg_func},
    {"rmr_req", ECPRI_RMR_REQ_STR, ecpri_rmr_req_func},
    {NULL, NULL, NULL}
}
ecpri_cmds The commands handled by the disable module.
Referenced by ecpri_func(), and ecpri_help_func().
long ecpri_report_limit = 0
OWDM measurement reporting limit (nsecs).
Referenced by ecpri_owdm_calc_delay(), and proto_ecpri_set_owdm_limit().
uint8_t owdm_comp[8] = {0, 0, 0, 0, 0, 0, 0, 0}
OWDM local delay compensation value.
Referenced by proto_ecpri_handle_incoming_owdm(), and proto_ecpri_owdm_send_req_get_ts().
owdm_ts_msg_type owdm_msg
OWDM message storage.
Referenced by proto_ecpri_handle_incoming_owdm(), and proto_ecpri_owdm_send_req_get_ts().
int owdm_req = 0
Number of OWDM requests sent by this node.
Referenced by proto_ecpri_get_owdm_result(), proto_ecpri_handle_incoming_owdm(), and proto_ecpri_owdm_send_request().
owdm_result_type owdm_result
OWDM result storage.
Referenced by proto_ecpri_get_owdm_result(), and proto_ecpri_handle_incoming_owdm().
int SEQ_NUM = 0
Sequence number for eCPRI test messages.
Referenced by proto_ecpri_test_mesg_send().